import fs from 'node:fs';
const root='.worktrees/v25-prior-waits/.claude/scripts/';
let entry=fs.readFileSync(root+'session-open.mjs','utf8');
const start=entry.indexOf('    // A sealed prior-mission wait stays historical.');
const end=entry.indexOf('\n  }\n  return false;',start);
if(start<0||end<0)throw Error('missing block');
const original=entry.slice(start,end);
const body=original.replaceAll('return true','return false').replace('await realpath(session)','realpathSync(session)').replace('await realpath(branch)','realpathSync(branch)').replaceAll('digest(', 'sha(').replace(/      const digest = value =>[^\n]+\n/,'');
let waiting=fs.readFileSync(root+'resolved-waiting.mjs','utf8');
const insert=`\n// A historical wait is retained evidence, never credit for the corrected mission.\nexport async function isSealedPriorMissionWait(session, state, key, attempt) {\n  if (attempt?.status !== 'waiting') return false;\n${body}\n  return true;\n}\n`;
waiting=waiting.replace('export async function resolvedWaitingAttemptKeys',insert+'\nexport async function resolvedWaitingAttemptKeys');
waiting=waiting.replace("    if (retiredPlanCell(state, parentKey))", "    if (Number.isInteger(parent.expected?.goalVersion) && parent.expected.goalVersion < state.mission.version) {\n      if (await isSealedPriorMissionWait(session, state, parentKey, parent)) retired.add(parentKey);\n      else errors.push(`REVIEW_REENTRY_UNBOUND: prior-mission wait ${parentKey} lacks intact sealed evidence`);\n      continue;\n    }\n    if (retiredPlanCell(state, parentKey))");
entry=entry.slice(0,start)+"    const { isSealedPriorMissionWait } = await import('./resolved-waiting.mjs');\n    if (!await isSealedPriorMissionWait(session, state, key, attempt)) return true;"+entry.slice(end);
fs.writeFileSync(root+'session-open.mjs',entry); fs.writeFileSync(root+'resolved-waiting.mjs',waiting);
