import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
import {missionCorrectionBusy} from './.claude/scripts/session-open.mjs';
import {resolvedWaitingAttemptKeys} from './.claude/scripts/resolved-waiting.mjs';
const session='D:/Repositories/nivo-backend/.worktrees/sessions/20260905160512-nivo-ca563924';
const state=JSON.parse(fs.readFileSync(path.join(session,'state.json')));
const files=['state.json',...Object.values(state.attempts).filter(a=>a.status==='waiting').flatMap(a=>[a.requestRef,a.responseRef]).filter(Boolean)];
const hashes=()=>Object.fromEntries(files.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(path.join(session,f))).digest('hex')]));
const before=hashes();const result=await resolvedWaitingAttemptKeys(path.resolve('.worktrees/v25-prior-waits/.claude'),session,state);
const busy=await missionCorrectionBusy(session,state);const after=hashes();
console.log(JSON.stringify({version:state.mission.version,busy,retired:[...result.retired],settled:[...result.settled],errors:result.errors,preserved:JSON.stringify(before)===JSON.stringify(after),files:files.length},null,2));
