import fs from 'node:fs';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { validateMigrationContract as before } from '../../.claude/scripts/migration-contract.mjs';
import { validateMigrationContract as after } from './.claude/scripts/migration-contract.mjs';
const root='D:/Repositories/starci-academy-backend/.claude';
const session='D:/Repositories/nivo-backend/.worktrees/sessions/20260905-nivo-accounting-01a07247';
const branch=session+'/step-32/parallel-1';
const requestFile=branch+'/request/request.json';
const requestBytes=fs.readFileSync(requestFile);
const request=JSON.parse(requestBytes);
const model=JSON.parse(fs.readFileSync(session+'/step-30/parallel-1/response/data/stack-model.json'));
const selected=model.operations.find(item=>item.operationId==='migrate-accounting-schema');
const mutations={contractFingerprint:request.requirements.contractFingerprint,operations:[selected]};
const results=[];
async function run(name,fn,req,output,pass){
 const result=await fn(root,branch,req,output);
 assert.equal(result.errors.length===0,pass,`${name}: ${result.errors.join('; ')}`);
 results.push({name,passed:true,errors:result.errors,operations:result.operations.map(item=>item.operationId)});
}
await run('published full-model gate reproduces the unit deadlock',before,request,mutations,false);
await run('current accepted plan scopes the selected migration',after,request,mutations,true);
await run('missing selected operation refused',after,request,{...mutations,operations:[]},false);
await run('dependent foreign operation refused',after,request,{...mutations,operations:[selected,model.operations.find(item=>item!==selected)]},false);
await run('changed frozen writer refused',after,request,{...mutations,operations:[{...selected,writerRef:'src/foreign.ts'}]},false);
await run('unknown selected unit refused',after,{...request,unit:'unknown-unit'},mutations,false);
await run('missing plan binding refused',after,{...request,inputs:{...request.inputs,units:undefined}},mutations,false);
const unsplit={...request};delete unsplit.unit;
await run('unsplit contract still requires all operations',after,unsplit,mutations,false);
const narrowed={...request,requirements:{...request.requirements,mutableFileRefs:[selected.writerRef,...selected.migrationRefs]}};
await run('unit checks only its own migration write roots',after,narrowed,mutations,true);
assert.deepEqual(fs.readFileSync(requestFile),requestBytes,'probe never edits the peer request');
const report={observedAt:new Date().toISOString(),requestSha256:createHash('sha256').update(requestBytes).digest('hex'),kind:'read-only actual accepted-plan regression; not product execution',results};
fs.writeFileSync(new URL('./actual-probe.json',import.meta.url),JSON.stringify(report,null,2)+'\n');
console.log(`${results.length}/${results.length} actual read-only cases passed`);
