import fs from 'node:fs';
const base='./.claude/';
for(const name of ['INDEX.md','INDEX.vi.md']){
 let text=fs.readFileSync(base+name,'utf8').replace('2.5.0-rc.2','2.5.0-rc.3');
 const line=name==='INDEX.md'?'2.5.0-rc.3 (2026-09-06): sealed nested return and disclosed review-integrity concerns re-enter through a fresh same-owner invocation and independent review, preserving original proof and current goal authority.':'2.5.0-rc.3 (2026-09-06): nested return đã niêm phong và vấn đề toàn vẹn review đã khai báo vào lại qua invocation cùng owner và review độc lập mới, giữ nguyên proof gốc cùng quyền hạn goal hiện tại.';
 text=text.replace(/(## (?:Lineage|Lịch sử)[^\n]*\n)/, '$1\n'+line+'\n');
 fs.writeFileSync(base+name,text);
}
const pkg=JSON.parse(fs.readFileSync(base+'package.json'));pkg.version='2.5.0-rc.3';fs.writeFileSync(base+'package.json',JSON.stringify(pkg,null,2)+'\n');
const paragraphs={
 'README.md':`\nA waiting node whose exact sealed nested review selects its kind contract's \`reentry\` verdict uses the same \`resume\` edit. The forecast retains the parent/child attempt identities, request hashes, evidence fingerprints and current scope. It opens a new same-owner invocation; neither accepted checkpoint is resumed or rewritten in place. The replacement must produce its own model and receive its own fresh matched nested review before it can conclude. A planned replacement remains an outstanding obligation and supplies no completion evidence.\n\nWhen the owning execution discloses a review-integrity concern, add \`integrity: {ref, hash}\` to that edit. The session-relative JSON disclosure has exactly \`version: 1\`, \`identity\`, \`disposition: "fresh-review-required"\`, a concrete \`reason\`, and the actual admission's \`sourceRef\`. Its identity binds \`sessionId\`, \`missionVersion\`, \`scopeHash\`, and \`parent\`/\`child\` records containing \`cell\`, \`attemptId\`, \`requestHash\`, and \`evidenceFingerprint\`. The hash covers the exact disclosure bytes, retained in the sealed forecast. This record authorizes only fresh review within the existing confirmed scope: it is neither a review verdict nor an approval or delivery input. Preserve the questioned evidence and its admitted limitation; no filesystem timestamp substitutes for execution provenance.\n`,
 'README.vi.md':`\nNode waiting có nested review đã niêm phong chọn verdict \`reentry\` do kind contract khai báo dùng cùng edit \`resume\`. Dự báo giữ identity attempt cha/con, hash request, fingerprint evidence và scope hiện tại. Nó mở invocation mới cùng owner; không resume hay sửa checkpoint đã chấp nhận tại chỗ. Invocation thay thế phải tạo model của chính nó và có nested review mới matched trước khi kết luận. Nhánh thay thế mới được lên kế hoạch vẫn là nghĩa vụ chưa hoàn thành, không cấp proof hoàn tất.\n\nKhi execution sở hữu công việc khai báo vấn đề toàn vẹn review, thêm \`integrity: {ref, hash}\` vào edit đó. JSON disclosure tương đối với session có đúng \`version: 1\`, \`identity\`, \`disposition: "fresh-review-required"\`, \`reason\` cụ thể và \`sourceRef\` của lời thừa nhận thật. Identity bind \`sessionId\`, \`missionVersion\`, \`scopeHash\`, cùng bản ghi \`parent\`/\`child\` chứa \`cell\`, \`attemptId\`, \`requestHash\` và \`evidenceFingerprint\`. Hash bao phủ nguyên byte disclosure, được lưu trong dự báo niêm phong. Bản ghi chỉ cho phép review mới trong scope đã xác nhận: không phải verdict review, approval hay input delivery. Giữ evidence bị đặt nghi vấn và giới hạn đã thừa nhận; timestamp filesystem không thay thế provenance execution.\n`
};
for(const [name,addition] of Object.entries(paragraphs)){
 let text=fs.readFileSync(base+'workflows/'+name,'utf8');
 if(name==='README.md')text=text.replace('The owning lock refuses any running or waiting invocation and active lease.','The owning lock refuses running invocations, active leases and waiting obligations not resolved by the exact review re-entry below.');
 else text=text.replace('Lock owner từ chối khi còn invocation chạy/chờ hoặc lease đang giữ.','Lock owner từ chối invocation đang chạy, lease đang giữ và nghĩa vụ waiting chưa được giải quyết qua review re-entry chính xác bên dưới.');
 fs.writeFileSync(base+'workflows/'+name,text+addition);
}
