sonar.projectKey=starci-academy-backend
sonar.projectName=StarCi Academy Backend
sonar.sourceEncoding=UTF-8

sonar.sources=src,apps
sonar.tests=src,apps
sonar.exclusions=**/*.spec.ts,**/*.int-spec.ts,**/*.e2e-spec.ts,**/*.harness-spec.ts,**/dist/**,**/coverage/**
sonar.test.inclusions=**/*.spec.ts,**/*.int-spec.ts,**/*.e2e-spec.ts,**/*.harness-spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
