events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=5s;

    server {
        listen 80;

        location /api/search {
            set $search_upstream http://search-service:3000;
            proxy_pass $search_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/payment {
            set $payment_upstream http://payment-service:3000;
            proxy_pass $payment_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}

