import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
const home=path.resolve('.worktrees/v25-rc11-release'),dest=path.join(home,'.claude'),baseline='5f874f80bac7617c19de75173f951e5e1c80ec8a';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
function load(file,digest){const bytes=fs.readFileSync(file);if(sha(bytes)!==digest)throw Error('Manifest drift '+file);const m=JSON.parse(bytes);if(m.baseline!==baseline)throw Error('Baseline mismatch');return m;}
const unitFile='.worktrees/v25-unit-successors/review-manifest-rc11.json';const unit=load(unitFile,'8107cc955236868818c7790688cf287a12c6d9dfb3e4e002bf18b8a29c1b34a9');
const lifeFile='.worktrees/v25-prior-waits-lifecycle/review-manifest.json';const life=load(lifeFile,'2c613b09b5c2de14f9c8b190578d31dd6ac459d359b8d1845096cc1a1ccf8b58');
const writes=[...unit.files.map(f=>({path:f.file,source:path.join(unit.candidate,f.file),hash:f.sha256})),...life.prerequisites.map(f=>({path:f.path,source:path.resolve('.worktrees/v25-prior-waits/.claude',f.path),hash:f.sha256.replace('sha256:','')})),...life.files.map(f=>({path:f.path,source:f.source,hash:f.after.replace('sha256:','')}))];
const names=new Set();const prepared=writes.map(w=>{if(names.has(w.path))throw Error('Collision '+w.path);names.add(w.path);const target=path.resolve(dest,w.path);if(!target.startsWith(dest+path.sep))throw Error('Path');const bytes=fs.readFileSync(w.source);if(sha(bytes)!==w.hash)throw Error('Source drift '+w.path);return{...w,target,bytes};});
for(const w of prepared){fs.mkdirSync(path.dirname(w.target),{recursive:true});fs.writeFileSync(w.target,w.bytes);}
const integration={baseline,diagram:JSON.parse(fs.readFileSync(path.join(home,'diagram-integration.json'))),unit:{manifest:unitFile,sha256:sha(fs.readFileSync(unitFile))},priorWaits:{manifest:lifeFile,sha256:sha(fs.readFileSync(lifeFile))},paths:prepared.map(({path,hash})=>({path,hash})),readback:prepared.every(w=>sha(fs.readFileSync(w.target))===w.hash)};
fs.writeFileSync(path.join(home,'integration.json'),JSON.stringify(integration,null,2)+'\n');console.log('Integrated '+prepared.length+' paths alongside diagram, readback '+integration.readback);
