import fs from 'node:fs';
import path from 'node:path';
const home=import.meta.dirname,root=path.join(home,'.claude'),donor=path.resolve(home,'../v25-prior-waits/.claude');
for(const ref of ['scripts/resolved-waiting.mjs','scripts/session-open.mjs','scripts/session-correction.spec.mjs'])fs.copyFileSync(path.join(donor,ref),path.join(root,ref));
const file=path.join(root,'scripts/nested-return.spec.mjs'),text=fs.readFileSync(file,'utf8');
const start=text.indexOf('async function fixture('),end=text.indexOf('\nasync function replacementLifecycle');
if(start<0||end<start)throw Error('fixture boundary missing');
const prefix=text.slice(0,start).replace("import test from 'node:test';\n",'');
fs.writeFileSync(path.join(root,'scripts/nested-return-fixture.mjs'),prefix+text.slice(start,end).replace('async function fixture(','export async function fixture('));
fs.writeFileSync(file,text.slice(0,start)+"import { fixture } from './nested-return-fixture.mjs';\n"+text.slice(end));
