server:
  port: 3000

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:sql_nosql_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:Cuong123_A}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/sql_nosql_db}
