apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: api-service-so
spec:
  scaleTargetRef:
    name: api-service
  pollingInterval: 15
  cooldownPeriod: 90
  minReplicaCount: 1
  maxReplicaCount: 12
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server:9090
        metricName: http_requests_per_second_1m
        threshold: "100"
        query: sum by (app) (rate(http_requests_total{app="api-service"}[1m]))
