import {
    DynamicModule, Module
} from "@nestjs/common"
import {
    TypeOrmModule as NestTypeOrmModule
} from "@nestjs/typeorm"
import {
    ConfigurableModuleClass,
    OPTIONS_TYPE
} from "./primary.module-definition"
import {
    envConfig
} from "@modules/env"
import {
    POSTGRESQL_PRIMARY
} from "./constants"
import {
    InMemoryQueryResultCache
} from "./cache"
import {
    ContentEntity,
    ContentTranslationEntity,
    CodeExplainingEntity,
    CodeExplainingTranslationEntity,
    CodeImplementationEntity,
    CodeImplementationTranslationEntity,
    ContentBodyEntity,
    ContentBodyTranslationEntity,
    ContentLearningOutcomeEntity,
    ContentLearningOutcomeTranslationEntity,
    ChallengeEntity,
    ChallengeTranslationEntity,
    ChallengeRequirementEntity,
    ChallengeRequirementLangEntity,
    ChallengeRequirementLangTranslationEntity,
    ChallengeStepEntity,
    ChallengeStepLangEntity,
    ChallengeStepLangTranslationEntity,
    ChallengeOutputEntity,
    ChallengeOutputLangEntity,
    ChallengeOutputLangTranslationEntity,
    ChallengePrerequisiteEntity,
    ChallengePrerequisiteLangEntity,
    ChallengePrerequisiteLangTranslationEntity,
    ChallengeSubmissionPromptEntity,
    ChallengeSubmissionPromptTranslationEntity,
    CourseEntity,
    CourseMetadataEntity,
    CourseTranslationEntity,
    PreviewContentEntity,
    PreviewContentTranslationEntity,
    PricingPhaseEntity,
    PrerequisiteEntity,
    PrerequisiteTranslationEntity,
    QnaEntity,
    QnaTranslationEntity,
    LivestreamSessionEntity,
    LivestreamSessionTranslationEntity,
    JobEntity,
    ModuleEntity,
    ModuleTranslationEntity,
    TransactionEntity,
    EnrollmentEntity,
    ResourceEntity,
    ChallengeSubmissionEntity,
    ChallengeSubmissionTranslationEntity,
    ChallengeSubmissionApproachCriteriaEntity,
    ChallengeSubmissionApproachCriteriaLangEntity,
    ChallengeSubmissionOutcomeCriteriaEntity,
    ChallengeSubmissionOutcomeCriteriaLangEntity,
    UserChallengeSubmissionEntity,
    UserChallengeSubmissionAttemptEntity,
    UserChallengeSubmissionFeedbackEntity,
    CreditUsageHistoryEntity,
    XpHistoryEntity,
    UserEntity,
    ValuePropositionEntity,
    ValuePropositionTranslationEntity,
    UserCVSubmissionEntity,
    UserCVSubmissionAttemptEntity,
    SyncStateEntity,
    UserMilestoneTaskEntity,
    UserMilestoneTaskAttemptEntity,
    UserMilestoneTaskAttemptFeedbackEntity,
    MilestoneEntity,
    MilestoneTranslationEntity,
    MilestoneTaskEntity,
    MilestoneTaskTranslationEntity,
    MilestoneTaskCriteriaEntity,
    MilestoneTaskCriteriaTranslationEntity,
    MilestoneTaskCodeImplementationEntity,
    MilestoneTaskCodeImplementationTranslationEntity,
    MilestoneTaskOutcomeCriteriaEntity,
    MilestoneTaskOutcomeCriteriaLangEntity,
    MilestoneTaskApproachCriteriaEntity,
    MilestoneTaskApproachCriteriaLangEntity,
    MilestoneTaskBriefEntity,
    MilestoneTaskBriefTranslationEntity,
    UserContentEntity,
    UserFollowEntity,
    ActivityEntity,
    UserCourseProgressProjectionEntity,
    UserCourseProgressProjectionTranslationEntity,
    UserChallengeProgressProjectionEntity,
    ContentEngagementProjectionEntity,
    ContentEngagementProjectionTranslationEntity,
    UserStatsProjectionEntity,
    UserStatsProjectionTranslationEntity,
    CourseStatsProjectionEntity,
    CourseStatsProjectionTranslationEntity,
    AdvertisementEntity,
    ChangelogEntryEntity,
    BlogPostEntity,
    LeagueCohortEntity,
    UserLeagueEntity,
    AchievementEntity,
    UserAchievementEntity,
    UserContributionProjectionEntity,
    UserAchievementProjectionEntity,
    UserCodingProjectionEntity,
    UserXpProjectionEntity,
    UserCapstoneProjectionEntity,
    UserPinnedProjectsProjectionEntity,
    UserSolvedChallengesProjectionEntity,
    TrendingContentsProjectionEntity,
    LeagueCohortPointsProjectionEntity,
    FlashcardReviewEventEntity,
    UserFlashcardStatsProjectionEntity,
    TemplateCVEntity,
    TemplateCVTranslationEntity,
    FoundationCategoryEntity,
    FoundationCategoryTranslationEntity,
    FoundationEntity,
    FoundationTranslationEntity,
    FoundationTagEntity,
    FoundationTagTranslationEntity,
    HeadhuntingCompanyEntity,
    HeadhuntingCompanyTranslationEntity,
    ConsultantEntity,
    ConsultantTranslationEntity,
    AiModelEntity,
    AiModelTranslationEntity,
    AiSubscriptionEntity,
    MembershipEntity,
    CodingProblemEntity,
    CodingProblemTranslationEntity,
    CodingProblemTestcaseEntity,
    CodingProblemStarterCodeEntity,
    CodingProblemSolutionEntity,
    CodingSolutionRevealEntity,
    CodingSubmissionEntity,
    DeviceEntity,
    LoginSessionEntity,
    FlashcardDeckEntity,
    FlashcardDeckTranslationEntity,
    FlashcardCardEntity,
    FlashcardCardTranslationEntity,
    UserFlashcardReviewEntity,
    InterviewAttemptEntity,
    RagPlaygroundSessionEntity,
    StreakProtectedDayEntity,
    RewardRedemptionEntity,
    DailyQuestCompletionEntity,
    ContentReactionEntity,
    ContentAiSessionEntity,
    ContentAiMessageEntity,
    ActivityReactionEntity,
    ContentCommentEntity,
    CommentReactionEntity,
    CommunityPostEntity,
    CommunityPostCommentEntity,
    CommunityPostReactionEntity,
    CommunityPostCommentReactionEntity,
    ChatConversationEntity,
    ChatMessageEntity,
    AiLabPlaygroundEntity,
    AiLabPlaygroundTranslationEntity,
    AiLabRunEntity,
    AiLabEvalSetEntity,
    AiLabEvalCaseEntity,
    AiLabEvalRunEntity,
    AiLabEvalCaseResultEntity,
    NotificationEntity,
    UserPinnedProjectEntity,
    JobPostingEntity
} from "./entities"
import {
    ResolversModule
} from "./resolvers"
import {
    HydrationModule
} from "./hydration"
import {
    SyncStateService
} from "./sync-state.service"
import {
    PostgreSqlAdvisoryLockService
} from "./lock"

/**
 * Primary PostgreSQL module for the primary PostgreSQL connection.
 */
@Module({
})
export class PrimaryPostgreSQLModule extends ConfigurableModuleClass {
    /**
     * Register.
     * @param options - Options.
     * @returns Dynamic module.
     */
    public static register(
        options: typeof OPTIONS_TYPE = {
        }
    ): DynamicModule {
        const dynamicModule = super.register(options)
        const extraModules: Array<DynamicModule> = []
        if (options.withHydration !== false) {
            extraModules.push(
                HydrationModule.register({
                    isGlobal: options.isGlobal
                }),
            )
        }
        if (options.withResolvers) {
            extraModules.push(
                ResolversModule.register({
                    isGlobal: options.isGlobal
                })
            )
        }
        return {
            ...dynamicModule,
            imports: [
                NestTypeOrmModule.forRootAsync(
                    {
                        name: POSTGRESQL_PRIMARY,
                        useFactory: async () => {
                            const {
                                database,
                                host,
                                password,
                                port,
                                username,
                                synchronize
                            } = envConfig().databases.postgresql.primary
                            return {
                                type: "postgres",
                                host,
                                port,
                                username,
                                password,
                                database,
                                entities: [
                                    UserEntity,
                                    ValuePropositionEntity,
                                    ValuePropositionTranslationEntity,
                                    CourseEntity,
                                    CourseMetadataEntity,
                                    CourseTranslationEntity,
                                    PricingPhaseEntity,
                                    PrerequisiteEntity,
                                    PrerequisiteTranslationEntity,
                                    QnaEntity,
                                    QnaTranslationEntity,
                                    JobEntity,
                                    ModuleEntity,
                                    ModuleTranslationEntity,
                                    ContentEntity,
                                    ContentTranslationEntity,
                                    CodeExplainingEntity,
                                    CodeExplainingTranslationEntity,
                                    CodeImplementationEntity,
                                    CodeImplementationTranslationEntity,
                                    ContentBodyEntity,
                                    ContentBodyTranslationEntity,
                                    ContentLearningOutcomeEntity,
                                    ContentLearningOutcomeTranslationEntity,
                                    ChallengeEntity,
                                    ChallengeTranslationEntity,
                                    ChallengeRequirementEntity,
                                    ChallengeRequirementLangEntity,
                                    ChallengeRequirementLangTranslationEntity,
                                    ChallengeStepEntity,
                                    ChallengeStepLangEntity,
                                    ChallengeStepLangTranslationEntity,
                                    ChallengeOutputEntity,
                                    ChallengeOutputLangEntity,
                                    ChallengeOutputLangTranslationEntity,
                                    ChallengePrerequisiteEntity,
                                    ChallengePrerequisiteLangEntity,
                                    ChallengePrerequisiteLangTranslationEntity,
                                    ChallengeSubmissionPromptEntity,
                                    ChallengeSubmissionPromptTranslationEntity,
                                    ChallengeSubmissionApproachCriteriaEntity,
                                    ChallengeSubmissionApproachCriteriaLangEntity,
                                    ChallengeSubmissionOutcomeCriteriaEntity,
                                    ChallengeSubmissionOutcomeCriteriaLangEntity,
                                    PreviewContentEntity,
                                    PreviewContentTranslationEntity,
                                    LivestreamSessionEntity,
                                    LivestreamSessionTranslationEntity,
                                    TransactionEntity,
                                    EnrollmentEntity,
                                    ResourceEntity,
                                    ChallengeSubmissionEntity,
                                    ChallengeSubmissionTranslationEntity,
                                    UserChallengeSubmissionEntity,
                                    UserChallengeSubmissionAttemptEntity,
                                    UserChallengeSubmissionFeedbackEntity,
                                    CreditUsageHistoryEntity,
                                    XpHistoryEntity,
                                    UserCVSubmissionEntity,
                                    UserCVSubmissionAttemptEntity,
                                    SyncStateEntity,
                                    UserMilestoneTaskEntity,
                                    UserMilestoneTaskAttemptEntity,
                                    UserMilestoneTaskAttemptFeedbackEntity,
                                    MilestoneEntity,
                                    MilestoneTranslationEntity,
                                    MilestoneTaskEntity,
                                    MilestoneTaskTranslationEntity,
                                    MilestoneTaskCriteriaEntity,
                                    MilestoneTaskCriteriaTranslationEntity,
                                    MilestoneTaskCodeImplementationEntity,
                                    MilestoneTaskCodeImplementationTranslationEntity,
                                    MilestoneTaskOutcomeCriteriaEntity,
                                    MilestoneTaskOutcomeCriteriaLangEntity,
                                    MilestoneTaskApproachCriteriaEntity,
                                    MilestoneTaskApproachCriteriaLangEntity,
                                    MilestoneTaskBriefEntity,
                                    MilestoneTaskBriefTranslationEntity,
                                    UserContentEntity,
                                    UserFollowEntity,
                                    ActivityEntity,
                                    UserCourseProgressProjectionEntity,
                                    UserCourseProgressProjectionTranslationEntity,
                                    UserChallengeProgressProjectionEntity,
                                    ContentEngagementProjectionEntity,
                                    ContentEngagementProjectionTranslationEntity,
                                    UserStatsProjectionEntity,
                                    UserStatsProjectionTranslationEntity,
                                    CourseStatsProjectionEntity,
                                    CourseStatsProjectionTranslationEntity,
                                    AdvertisementEntity,
                                    ChangelogEntryEntity,
                                    BlogPostEntity,
                                    LeagueCohortEntity,
                                    UserLeagueEntity,
                                    AchievementEntity,
                                    UserAchievementEntity,
                                    UserContributionProjectionEntity,
                                    UserAchievementProjectionEntity,
                                    UserCodingProjectionEntity,
                                    UserXpProjectionEntity,
                                    UserCapstoneProjectionEntity,
                                    UserPinnedProjectsProjectionEntity,
                                    UserSolvedChallengesProjectionEntity,
                                    TrendingContentsProjectionEntity,
                                    LeagueCohortPointsProjectionEntity,
                                    FlashcardReviewEventEntity,
                                    UserFlashcardStatsProjectionEntity,
                                    TemplateCVEntity,
                                    TemplateCVTranslationEntity,
                                    FoundationCategoryEntity,
                                    FoundationCategoryTranslationEntity,
                                    FoundationEntity,
                                    FoundationTranslationEntity,
                                    FoundationTagEntity,
                                    FoundationTagTranslationEntity,
                                    HeadhuntingCompanyEntity,
                                    HeadhuntingCompanyTranslationEntity,
                                    ConsultantEntity,
                                    ConsultantTranslationEntity,
                                    AiModelEntity,
                                    AiModelTranslationEntity,
                                    AiSubscriptionEntity,
                                    MembershipEntity,
                                    CodingProblemEntity,
                                    CodingProblemTranslationEntity,
                                    CodingProblemTestcaseEntity,
                                    CodingProblemStarterCodeEntity,
                                    CodingProblemSolutionEntity,
                                    CodingSolutionRevealEntity,
                                    CodingSubmissionEntity,
                                    DeviceEntity,
                                    LoginSessionEntity,
                                    FlashcardDeckEntity,
                                    FlashcardDeckTranslationEntity,
                                    FlashcardCardEntity,
                                    FlashcardCardTranslationEntity,
                                    UserFlashcardReviewEntity,
                                    InterviewAttemptEntity,
                                    RagPlaygroundSessionEntity,
                                    StreakProtectedDayEntity,
                                    RewardRedemptionEntity,
                                    DailyQuestCompletionEntity,
                                    ContentReactionEntity,
                                    ContentAiSessionEntity,
                                    ContentAiMessageEntity,
                                    ActivityReactionEntity,
                                    ContentCommentEntity,
                                    CommentReactionEntity,
                                    CommunityPostEntity,
                                    CommunityPostCommentEntity,
                                    CommunityPostReactionEntity,
                                    CommunityPostCommentReactionEntity,
                                    ChatConversationEntity,
                                    ChatMessageEntity,
                                    AiLabPlaygroundEntity,
                                    AiLabPlaygroundTranslationEntity,
                                    AiLabRunEntity,
                                    AiLabEvalSetEntity,
                                    AiLabEvalCaseEntity,
                                    AiLabEvalRunEntity,
                                    AiLabEvalCaseResultEntity,
                                    NotificationEntity,
                                    UserPinnedProjectEntity,
                                    JobPostingEntity,
                                ],
                                synchronize,
                                logging: false,
                                cache: {
                                    provider(dataSource) {
                                        return new InMemoryQueryResultCache(dataSource)
                                    }
                                }
                            }
                        }
                    }
                ),
                this.forFeature(),
                ...extraModules,
            ],
            providers: [
                SyncStateService,
                PostgreSqlAdvisoryLockService,
            ],
            exports: [
                ...extraModules,
                SyncStateService,
                PostgreSqlAdvisoryLockService,
            ]
        }
    }

    /**
     * For feature.
     * @param options - Options.
     * @returns Dynamic module.
     */
    private static forFeature(
    ): DynamicModule {
        return {
            module: PrimaryPostgreSQLModule,
            imports: [
                NestTypeOrmModule.forFeature(
                    [
                        UserEntity,
                        ValuePropositionEntity,
                        ValuePropositionTranslationEntity,
                        CourseEntity,
                        CourseMetadataEntity,
                        CourseTranslationEntity,
                        PricingPhaseEntity,
                        PrerequisiteEntity,
                        PrerequisiteTranslationEntity,
                        QnaEntity,
                        QnaTranslationEntity,
                        JobEntity,
                        ModuleEntity,
                        ModuleTranslationEntity,
                        ContentEntity,
                        ContentTranslationEntity,
                        CodeExplainingEntity,
                        CodeExplainingTranslationEntity,
                        CodeImplementationEntity,
                        CodeImplementationTranslationEntity,
                        ContentBodyEntity,
                        ContentBodyTranslationEntity,
                        ContentLearningOutcomeEntity,
                        ContentLearningOutcomeTranslationEntity,
                        ChallengeEntity,
                        ChallengeTranslationEntity,
                        ChallengeRequirementEntity,
                        ChallengeRequirementLangEntity,
                        ChallengeRequirementLangTranslationEntity,
                        ChallengeStepEntity,
                        ChallengeStepLangEntity,
                        ChallengeStepLangTranslationEntity,
                        ChallengeOutputEntity,
                        ChallengeOutputLangEntity,
                        ChallengeOutputLangTranslationEntity,
                        ChallengePrerequisiteEntity,
                        ChallengePrerequisiteLangEntity,
                        ChallengePrerequisiteLangTranslationEntity,
                        ChallengeSubmissionPromptEntity,
                        ChallengeSubmissionPromptTranslationEntity,
                        PreviewContentEntity,
                        PreviewContentTranslationEntity,
                        LivestreamSessionEntity,
                        LivestreamSessionTranslationEntity,
                        TransactionEntity,
                        EnrollmentEntity,
                        ResourceEntity,
                        ChallengeSubmissionEntity,
                        ChallengeSubmissionTranslationEntity,
                        UserChallengeSubmissionEntity,
                        UserChallengeSubmissionAttemptEntity,
                        UserChallengeSubmissionFeedbackEntity,
                        CreditUsageHistoryEntity,
                        XpHistoryEntity,
                        UserCVSubmissionEntity,
                        UserCVSubmissionAttemptEntity,
                        SyncStateEntity,
                        UserMilestoneTaskEntity,
                        UserMilestoneTaskAttemptEntity,
                        UserMilestoneTaskAttemptFeedbackEntity,
                        MilestoneEntity,
                        MilestoneTranslationEntity,
                        MilestoneTaskEntity,
                        MilestoneTaskTranslationEntity,
                        MilestoneTaskCriteriaEntity,
                        MilestoneTaskCriteriaTranslationEntity,
                        MilestoneTaskCodeImplementationEntity,
                        MilestoneTaskCodeImplementationTranslationEntity,
                        MilestoneTaskOutcomeCriteriaEntity,
                        MilestoneTaskOutcomeCriteriaLangEntity,
                        MilestoneTaskApproachCriteriaEntity,
                        MilestoneTaskApproachCriteriaLangEntity,
                        MilestoneTaskBriefEntity,
                        MilestoneTaskBriefTranslationEntity,
                        UserContentEntity,
                        UserFollowEntity,
                        ActivityEntity,
                        UserCourseProgressProjectionEntity,
                        UserCourseProgressProjectionTranslationEntity,
                        UserChallengeProgressProjectionEntity,
                        ContentEngagementProjectionEntity,
                        ContentEngagementProjectionTranslationEntity,
                        UserStatsProjectionEntity,
                        UserStatsProjectionTranslationEntity,
                        CourseStatsProjectionEntity,
                        CourseStatsProjectionTranslationEntity,
                        AdvertisementEntity,
                        ChangelogEntryEntity,
                        BlogPostEntity,
                        LeagueCohortEntity,
                        UserLeagueEntity,
                        AchievementEntity,
                        UserAchievementEntity,
                        UserContributionProjectionEntity,
                        UserAchievementProjectionEntity,
                        UserCodingProjectionEntity,
                        UserXpProjectionEntity,
                        UserCapstoneProjectionEntity,
                        UserPinnedProjectsProjectionEntity,
                        UserSolvedChallengesProjectionEntity,
                        TrendingContentsProjectionEntity,
                        LeagueCohortPointsProjectionEntity,
                        FlashcardReviewEventEntity,
                        UserFlashcardStatsProjectionEntity,
                        TemplateCVEntity,
                        TemplateCVTranslationEntity,
                        FoundationCategoryEntity,
                        FoundationCategoryTranslationEntity,
                        FoundationEntity,
                        FoundationTranslationEntity,
                        FoundationTagEntity,
                        FoundationTagTranslationEntity,
                        HeadhuntingCompanyEntity,
                        HeadhuntingCompanyTranslationEntity,
                        ConsultantEntity,
                        ConsultantTranslationEntity,
                        AiModelEntity,
                        AiModelTranslationEntity,
                        AiSubscriptionEntity,
                        MembershipEntity,
                        CodingProblemEntity,
                        CodingProblemTranslationEntity,
                        CodingProblemTestcaseEntity,
                        CodingProblemStarterCodeEntity,
                        CodingProblemSolutionEntity,
                        CodingSolutionRevealEntity,
                        CodingSubmissionEntity,
                        DeviceEntity,
                        LoginSessionEntity,
                        FlashcardDeckEntity,
                        FlashcardDeckTranslationEntity,
                        FlashcardCardEntity,
                        FlashcardCardTranslationEntity,
                        UserFlashcardReviewEntity,
                        InterviewAttemptEntity,
                        RagPlaygroundSessionEntity,
                        StreakProtectedDayEntity,
                        RewardRedemptionEntity,
                        DailyQuestCompletionEntity,
                        ContentReactionEntity,
                        ContentAiSessionEntity,
                        ContentAiMessageEntity,
                        ActivityReactionEntity,
                        ContentCommentEntity,
                        CommentReactionEntity,
                        CommunityPostEntity,
                        CommunityPostCommentEntity,
                        CommunityPostReactionEntity,
                        CommunityPostCommentReactionEntity,
                        ChatConversationEntity,
                        ChatMessageEntity,
                        AiLabPlaygroundEntity,
                        AiLabPlaygroundTranslationEntity,
                        AiLabRunEntity,
                        AiLabEvalSetEntity,
                        AiLabEvalCaseEntity,
                        AiLabEvalRunEntity,
                        AiLabEvalCaseResultEntity,
                        UserPinnedProjectEntity,
                        JobPostingEntity,
                    ],
                    POSTGRESQL_PRIMARY
                ),
            ]
        }
    }
}
