import {
    Field,
    Float,
    ID,
    ObjectType,
} from "@nestjs/graphql"
import {
    Column,
    Entity,
    JoinColumn,
    ManyToOne,
    RelationId,
} from "typeorm"
import {
    CvSubmissionStatus,
    GraphQLTypeCvSubmissionStatus,
} from "../enums"
import {
    UuidAbstractEntity,
} from "./abstract"
import {
    UserEntity,
} from "./user.entity"
import {
    CVPromptEntity,
} from "./cv-prompt.entity"

/**
 * Shape of a single spelling error returned by the LLM.
 */
export interface SpellError {
    /** The misspelled word. */
    word: string
    /** Suggested correction. */
    suggestion: string
    /** Approximate line number in the CV text (0 if unknown). */
    line: number
}

/**
 * Tracks one CV analysis request end-to-end:
 * file upload → text extraction → LLM analysis → result storage.
 *
 * Relations:
 *   users      1 ──── N   cv_submissions
 *   cv_prompts 1 ──── N   cv_submissions
 */
@ObjectType({
    description: "A user's CV submission and its LLM analysis result.",
})
@Entity("cv_submissions")
export class CVSubmissionEntity extends UuidAbstractEntity {
    /**
     * MinIO object key for the uploaded file (PDF or DOCX).
     * Format: `cv-submissions/<userId>/<uuid>.<ext>`
     */
    @Field(
        () => String,
        {
            description: "MinIO object key of the uploaded CV file.",
        },
    )
    @Column({
        name: "file_url",
        type: "varchar",
        length: 2048,
    })
        fileUrl: string

    /**
     * Raw text extracted from the PDF/DOCX file.
     * Cached here so the worker does not re-download on retry.
     */
    @Field(
        () => String,
        {
            nullable: true,
            description: "Raw text extracted from the CV file (cached).",
        },
    )
    @Column({
        name: "original_text",
        type: "text",
        nullable: true,
    })
        originalText: string | null

    /**
     * Current processing status of this submission.
     */
    @Field(
        () => GraphQLTypeCvSubmissionStatus,
        {
            description: "Current processing status.",
        },
    )
    @Column({
        name: "status",
        type: "enum",
        enum: CvSubmissionStatus,
        enumName: "cv_submission_status",
        default: CvSubmissionStatus.Pending,
    })
        status: CvSubmissionStatus

    // ─── Analysis result (populated by worker after Done) ────────────────────

    /**
     * 2–3 sentence professional summary generated by the LLM.
     */
    @Field(
        () => String,
        {
            nullable: true,
            description: "LLM-generated professional summary of the CV.",
        },
    )
    @Column({
        name: "summary",
        type: "text",
        nullable: true,
    })
        summary: string | null

    /**
     * List of 3–5 strengths identified in the CV.
     */
    @Field(
        () => [String],
        {
            nullable: true,
            description: "List of strengths identified in the CV.",
        },
    )
    @Column({
        name: "strength",
        type: "jsonb",
        nullable: true,
    })
        strength: Array<string> | null

    /**
     * List of 2–4 weaknesses identified in the CV.
     */
    @Field(
        () => [String],
        {
            nullable: true,
            description: "List of weaknesses identified in the CV.",
        },
    )
    @Column({
        name: "weakness",
        type: "jsonb",
        nullable: true,
    })
        weakness: Array<string> | null

    /**
     * 3–5 job titles suggested by the LLM based on the CV profile.
     */
    @Field(
        () => [String],
        {
            nullable: true,
            description: "Job titles suggested by the LLM.",
        },
    )
    @Column({
        name: "suggested_jobs",
        type: "jsonb",
        nullable: true,
    })
        suggestedJobs: Array<string> | null

    /**
     * Obvious spelling/typo errors found in the CV (max 10).
     * Each item has `{ word, suggestion, line }`.
     */
    @Field(
        () => String,
        {
            nullable: true,
            description: "JSON array of spell errors: [{ word, suggestion, line }].",
        },
    )
    @Column({
        name: "spell_errors",
        type: "jsonb",
        nullable: true,
    })
        spellErrors: Array<SpellError> | null

    /**
     * Holistic CV score 0–100 assigned by the LLM.
     */
    @Field(
        () => Float,
        {
            nullable: true,
            description: "Holistic CV score (0–100) assigned by the LLM.",
        },
    )
    @Column({
        name: "score",
        type: "float",
        nullable: true,
    })
        score: number | null

    /**
     * The user who submitted this CV.
     */
    @Field(
        () => UserEntity,
        {
            description: "User who submitted this CV.",
        },
    )
    @ManyToOne(
        () => UserEntity,
        {
            onDelete: "CASCADE",
        },
    )
    @JoinColumn({
        name: "user_id",
        foreignKeyConstraintName: "fk_user_id_cv_submissions_users",
    })
        user: UserEntity

    @Field(
        () => ID,
        {
            description: "ID of the user who submitted the CV.",
        },
    )
    @RelationId(
        (s: CVSubmissionEntity) => s.user,
    )
        userId: string

    /**
     * The prompt template used to analyse this submission.
     */
    @Field(
        () => CVPromptEntity,
        {
            nullable: true,
            description: "Prompt template used to analyse this CV.",
        },
    )
    @ManyToOne(
        () => CVPromptEntity,
        (prompt: CVPromptEntity) => prompt.submissions,
        {
            onDelete: "SET NULL",
            nullable: true,
        },
    )
    @JoinColumn({
        name: "cv_prompt_id",
        foreignKeyConstraintName: "fk_cv_prompt_id_cv_submissions_cv_prompts",
    })
        cvPrompt: CVPromptEntity | null

    @Field(
        () => ID,
        {
            nullable: true,
            description: "ID of the prompt template used.",
        },
    )
    @RelationId(
        (s: CVSubmissionEntity) => s.cvPrompt,
    )
        cvPromptId: string | null
}
