import {
    Field,
    ID,
    Int,
    ObjectType,
} from "@nestjs/graphql"
import {
    Column,
    Entity,
    JoinColumn,
    ManyToOne,
    RelationId,
} from "typeorm"
import {
    UuidAbstractEntity,
} from "./abstract"
import {
    UserEntity,
} from "./user.entity"
import {
    CourseEntity,
} from "./course.entity"
import {
    CvGenerationMode,
    GraphQLTypeCvGenerationMode,
} from "../enums/cv-generation-mode"
import {
    CvGenerationStatus,
    GraphQLTypeCvGenerationStatus,
} from "../enums/cv-generation-status"
import {
    CvSource,
    GraphQLTypeCvSource,
} from "../enums/cv-source"

@ObjectType({
    description: "A user's CV — generated by the system or uploaded — with optional customization + score.",
})
@Entity("cv_generations")
/**
 * **The unified "user CV"** — one row per CV the user owns, from either source
 * (`source`): **generated** (the system builds a CV from the user's free-text
 * input / verified StarCi achievements) or **uploaded** (the user brings their
 * own CV file in via `uploadedCdnKey`). Both live in this one `cv_generations`
 * table and share a single scoring rubric.
 *
 * **Generated pipeline** (background worker)
 * 1. **Assemble** — LLM reads `extraPrompts` (and, when `mode` = `Revise`, the
 *    source submission at `sourceCvSubmissionId`) → persist the structured CV
 *    JSON into `structuredData` (header / summary / skills / experience /
 *    education).
 * 2. **Render** — turn `structuredData` into a `.tex` document, upload to MinIO
 *    → persist the object key into `latexCdnKey`.
 *
 * **`status`** moves Pending → Processing → Done (or Failed, with
 * `errorMessage` populated).
 *
 * **Customization / scoring** — the user may name the CV (`label`), tie it to a
 * track (`courseId`, optional), and note a `targetRole` / `language`. `score`
 * (0–100) + `feedback` are filled by the shared scoring step (WF-03b); they are
 * intentionally nullable here so this schema pass adds the *place* to hold them
 * without any grading logic.
 *
 * **Relations**
 * ```
 * users   (1) ─────< cv_generations (N)
 * courses (1) ─────< cv_generations (N)   [optional]
 * ```
 */
export class UserCvGenerationEntity extends UuidAbstractEntity {
    /**
     * Owner user (`user_id` foreign key).
     */
    @Field(
        () => UserEntity,
        {
            description: "User who requested this CV generation.",
        },
    )
    @ManyToOne(
        () => UserEntity,
        {
            onDelete: "CASCADE",
        },
    )
    @JoinColumn({
        name: "user_id",
        foreignKeyConstraintName: "fk_user_id_cv_generations_users",
    })
        user: UserEntity

    @Field(
        () => ID,
        {
            description: "ID of the user who requested this CV generation.",
        },
    )
    @RelationId(
        (generation: UserCvGenerationEntity) => generation.user,
    )
        userId: string

    /**
     * Whether this run builds a new CV or revises an existing submission.
     */
    @Field(
        () => GraphQLTypeCvGenerationMode,
        {
            description: "Whether this run builds a new CV or revises an existing submission.",
        },
    )
    @Column({
        type: "enum",
        enum: CvGenerationMode,
        name: "mode",
        nullable: false,
    })
        mode: CvGenerationMode

    /**
     * Processing status of this generation run (defaults to `Pending`).
     */
    @Field(
        () => GraphQLTypeCvGenerationStatus,
        {
            description: "Processing status of this generation run.",
        },
    )
    @Column({
        type: "enum",
        enum: CvGenerationStatus,
        name: "status",
        nullable: false,
        default: CvGenerationStatus.Pending,
    })
        status: CvGenerationStatus

    /**
     * Origin of this CV: `generated` (built by the system) or `uploaded` (the
     * user brought their own file). Defaults to `generated` so pre-existing
     * generation rows remain valid after this schema pass.
     */
    @Field(
        () => GraphQLTypeCvSource,
        {
            description: "Origin of this CV (system-generated vs. user-uploaded).",
        },
    )
    @Column({
        type: "enum",
        enum: CvSource,
        name: "source",
        nullable: false,
        default: CvSource.Generated,
    })
        source: CvSource

    /**
     * When `mode` = `Revise`, the id of the earlier `cv_generations` row being
     * revised (`source_cv_submission_id` — legacy-named column, now points at
     * another `UserCvGenerationEntity`, not the removed legacy upload table).
     * Plain nullable uuid column (no FK relation) so the generation history
     * survives even if the source row is later deleted.
     */
    @Field(
        () => ID,
        {
            nullable: true,
            description: "ID of the source CV submission being revised (when mode = Revise).",
        },
    )
    @Column({
        name: "source_cv_submission_id",
        type: "uuid",
        nullable: true,
    })
        sourceCvSubmissionId: string | null

    /**
     * User's free-text input describing projects, skills, and experience
     * (e.g. "I built project A, project B, I know Golang / TypeScript…").
     */
    @Field(
        () => String,
        {
            nullable: true,
            description: "User's free-text input describing projects, skills, and experience.",
        },
    )
    @Column({
        name: "extra_prompts",
        type: "text",
        nullable: true,
    })
        extraPrompts: string | null

    /**
     * The assembled CV JSON (header / summary / skills / experience /
     * education) produced by the assemble step.
     */
    @Field(
        () => String,
        {
            nullable: true,
            description: "Assembled CV JSON (header/summary/skills/experience/education).",
        },
    )
    @Column({
        name: "structured_data",
        type: "jsonb",
        nullable: true,
    })
        structuredData: Record<string, unknown> | null

    /**
     * MinIO object key of the generated `.tex` file (`latex_cdn_key`).
     */
    @Field(
        () => String,
        {
            nullable: true,
            description: "MinIO object key of the generated .tex file.",
        },
    )
    @Column({
        name: "latex_cdn_key",
        type: "varchar",
        length: 2048,
        nullable: true,
    })
        latexCdnKey: string | null

    /**
     * MinIO object key of the PDF compiled (server-side, via `tectonic`) from
     * `latexCdnKey`'s `.tex` (`generated_pdf_cdn_key`). Set only for `Generated`
     * source rows whose compile step succeeded; null otherwise (pre-compile
     * rows, `Uploaded` source, or a failed compile — degrades to the raw
     * `.tex` download).
     */
    @Field(
        () => String,
        {
            nullable: true,
            description: "MinIO object key of the PDF compiled from the generated .tex (null until compiled or on Uploaded CVs).",
        },
    )
    @Column({
        name: "generated_pdf_cdn_key",
        type: "varchar",
        length: 2048,
        nullable: true,
    })
        generatedPdfCdnKey: string | null

    @Field(
        () => Date,
        {
            nullable: true,
            description: "When this generation run finished processing.",
        },
    )
    @Column({
        name: "processed_at",
        type: "timestamptz",
        nullable: true,
    })
        processedAt: Date | null

    /**
     * Error detail populated when `status` = `Failed`.
     */
    @Field(
        () => String,
        {
            nullable: true,
            description: "Error message populated when the generation fails.",
        },
    )
    @Column({
        name: "error_message",
        type: "text",
        nullable: true,
    })
        errorMessage: string | null

    /**
     * Optional course this CV is tied to (`course_id`). Lets the user organize a
     * CV per track; the fairness model reads MAX(score) per `courseId`. No
     * cascade — deleting the course nulls this out (`SET NULL`) so the CV row
     * survives. Optional relation: a CV need not belong to any track.
     */
    @Field(
        () => CourseEntity,
        {
            nullable: true,
            description: "Optional course/track this CV is tied to.",
        },
    )
    @ManyToOne(
        () => CourseEntity,
        {
            nullable: true,
            onDelete: "SET NULL",
        },
    )
    @JoinColumn({
        name: "course_id",
        foreignKeyConstraintName: "fk_course_id_cv_generations_courses",
    })
        course: CourseEntity | null

    /**
     * Id of the course this CV is tied to (`course_id`), or `null` when the CV
     * is not attached to any track.
     */
    @Field(
        () => ID,
        {
            nullable: true,
            description: "Id of the course this CV is tied to (null when untied).",
        },
    )
    @RelationId(
        (generation: UserCvGenerationEntity) => generation.course,
    )
        courseId: string | null

    /**
     * User-facing name for this CV (`label`), e.g. "Backend — Java". Nullable;
     * the frontend falls back to a generated name (e.g. "CV #n") when empty.
     */
    @Field(
        () => String,
        {
            nullable: true,
            description: "User-facing name for this CV (frontend falls back when empty).",
        },
    )
    @Column({
        name: "label",
        type: "varchar",
        length: 255,
        nullable: true,
    })
        label: string | null

    /**
     * Free-text target role the user is aiming this CV at (`target_role`), e.g.
     * "Senior Backend Engineer". Optional customization — no enforced taxonomy.
     */
    @Field(
        () => String,
        {
            nullable: true,
            description: "Target role this CV is aimed at (free-text; no enforced taxonomy).",
        },
    )
    @Column({
        name: "target_role",
        type: "varchar",
        length: 255,
        nullable: true,
    })
        targetRole: string | null

    /**
     * Language / locale hint the user wants this CV in (`language`), e.g. "en"
     * or "vi". Optional free-text — no enforced taxonomy.
     */
    @Field(
        () => String,
        {
            nullable: true,
            description: "Language/locale this CV is written in (free-text; no enforced taxonomy).",
        },
    )
    @Column({
        name: "language",
        type: "varchar",
        length: 64,
        nullable: true,
    })
        language: string | null

    /**
     * MinIO object key of the user's uploaded CV file (`uploaded_cdn_key`), set
     * when `source` = `uploaded`. Null for generated CVs.
     */
    @Field(
        () => String,
        {
            nullable: true,
            description: "MinIO object key of the user's uploaded CV file (when source = uploaded).",
        },
    )
    @Column({
        name: "uploaded_cdn_key",
        type: "varchar",
        length: 2048,
        nullable: true,
    })
        uploadedCdnKey: string | null

    /**
     * Holistic score (0–100) for this CV (`score`), filled by the shared scoring
     * step (WF-03b). Nullable until scored — no grading logic is added here.
     */
    @Field(
        () => Int,
        {
            nullable: true,
            description: "Holistic CV score (0–100); filled by the shared scoring step.",
        },
    )
    @Column({
        name: "score",
        type: "int",
        nullable: true,
    })
        score: number | null

    /**
     * Structured AI feedback for this CV (`feedback`), filled by the shared
     * scoring step (WF-03b). Nullable until scored.
     */
    @Field(
        () => String,
        {
            nullable: true,
            description: "Structured AI feedback JSON for this CV; filled by the shared scoring step.",
        },
    )
    @Column({
        name: "feedback",
        type: "jsonb",
        nullable: true,
    })
        feedback: Record<string, unknown> | null
}
