import {
    DynamicModule,
    Module,
} from "@nestjs/common"
import {
    ChallengeIdFactoryService,
    ChallengeSubmissionPromptIdFactoryService,
    ChallengeReferenceIdFactoryService,
    ChallengeStepIdFactoryService,
    ChallengeStepCodeImplementationIdFactoryService,
    ChallengeSubmissionIdFactoryService,
    ChallengeRequirementIdFactoryService,
    ChallengeOutputIdFactoryService,
    ChallengePrerequisiteIdFactoryService,
    ChallengeRequirementV2IdFactoryService,
    ChallengeStepV2IdFactoryService,
    ChallengeOutputV2IdFactoryService,
    ChallengePrerequisiteV2IdFactoryService,
    ContentIdFactoryService,
    ContentReferenceIdFactoryService,
    CodeExplainingIdFactoryService,
    CodeImplementationIdFactoryService,
    ContentBodyV2IdFactoryService,
    CourseIdFactoryService,
    LessonVideoIdFactoryService,
    LivestreamSessionIdFactoryService,
    ModuleIdFactoryService,
    PrerequisiteIdFactoryService,
    PreviewContentIdFactoryService,
    PricingPhaseIdFactoryService,
    QnaIdFactoryService,
    ValuePropositionIdFactoryService,
    ChallengeParserService,
    ChallengeV2ParserService,
    QuizDeckParserService,
    ContentParserService,
    CourseParserService,
    LessonVideoParserService,
    ModuleParserService,
    ChallengePathService,
    QuizDeckPathService,
    QuizDeckIdFactoryService,
    QuizCardIdFactoryService,
    QuizCardOptionIdFactoryService,
    UpsertService,
    CourseInsertService,
    ModuleInsertService,
    ContentInsertService,
    LessonVideoInsertService,
    ChallengeInsertService,
    ChallengeV2InsertService,
    QuizDeckInsertService,
    MilestoneIdFactoryService,
    MilestoneTaskIdFactoryService,
    MilestoneTaskPassCriteriaIdFactoryService,
    MilestoneTaskCodeImplementationIdFactoryService,
    MilestonePathService,
    MilestoneTaskPathService,
    MilestoneParserService,
    MilestoneTaskParserService,
    MilestoneInsertService,
    MilestoneTaskInsertService,
    MindMapParserService,
    MindMapInsertService,
    CourseSeederService,
    ContentPathService,
    CoursePathService,
    LessonVideoPathService,
    ModulePathService,
} from "./courses"
import {
    CvSeederService,
    TemplateCvIdFactoryService,
    TemplateCvInsertService,
    TemplateCvParserService,
    TemplateCvPathService,
} from "./cv"
import {
    FoundationSeederService,
    FoundationCategoryPathService,
    FoundationPathService,
    FoundationCategoryIdFactoryService,
    FoundationIdFactoryService,
    FoundationTagIdFactoryService,
    FoundationCategoryParserService,
    FoundationParserService,
    FoundationTagParserService,
    FoundationCategoryInsertService,
    FoundationInsertService,
} from "./foundations"
import {
    CatalogSeederService,
    AiModelCatalogPathService,
    SubscriptionCatalogPathService,
    AiModelCatalogParserService,
    SubscriptionCatalogParserService,
    AiModelInsertService,
} from "./catalog"
import {
    HeadhuntingSeederService,
    HeadhuntingCompanyPathService,
    ConsultantPathService,
    HeadhuntingCompanyIdFactoryService,
    ConsultantIdFactoryService,
    HeadhuntingCompanyParserService,
    ConsultantParserService,
    HeadhuntingCompanyInsertService,
    ConsultantInsertService,
} from "./headhuntings"
import {
    CodingProblemSeederService,
    CodingProblemPathService,
    CodingProblemParserService,
    CodingProblemInsertService,
} from "./coding-problems"
import {
    SeedersService,
} from "./seeders.service"
import {
    ConfigurableModuleClass, OPTIONS_TYPE 
} from "./seeders.module-definition"
import {
    ExtractJsonFromMdService,
    CoerceMdScalarService,
    S3ContextService,
    FilesystemContextService,
    ContextLoaderService,
    PathResolverService,
} from "./shared"


/**
 * Module for the Seeders.
 * Provides all parser services and the SeedersService.
 */
@Module({
})
export class SeedersModule extends ConfigurableModuleClass {
    static register(
        options: typeof OPTIONS_TYPE
    ): DynamicModule {
        const dynamicModule = super.register(options)
        const providers = [
            ExtractJsonFromMdService,
            CoerceMdScalarService,
            S3ContextService,
            FilesystemContextService,
            ContextLoaderService,
            CourseIdFactoryService,
            ModuleIdFactoryService,
            ContentIdFactoryService,
            ContentReferenceIdFactoryService,
            CodeExplainingIdFactoryService,
            CodeImplementationIdFactoryService,
            ContentBodyV2IdFactoryService,
            PreviewContentIdFactoryService,
            PricingPhaseIdFactoryService,
            ValuePropositionIdFactoryService,
            PrerequisiteIdFactoryService,
            QnaIdFactoryService,
            LessonVideoIdFactoryService,
            LivestreamSessionIdFactoryService,
            CoursePathService,
            ModulePathService,
            ContentPathService,
            LessonVideoPathService,
            ChallengePathService,
            QuizDeckPathService,
            QuizDeckIdFactoryService,
            QuizCardIdFactoryService,
            QuizCardOptionIdFactoryService,
            ChallengeIdFactoryService,
            ChallengeStepIdFactoryService,
            ChallengeStepCodeImplementationIdFactoryService,
            ChallengeReferenceIdFactoryService,
            ChallengeSubmissionIdFactoryService,
            ChallengeSubmissionPromptIdFactoryService,
            ChallengeRequirementIdFactoryService,
            ChallengeOutputIdFactoryService,
            ChallengePrerequisiteIdFactoryService,
            ChallengeRequirementV2IdFactoryService,
            ChallengeStepV2IdFactoryService,
            ChallengeOutputV2IdFactoryService,
            ChallengePrerequisiteV2IdFactoryService,
            CourseParserService,
            ModuleParserService,
            ContentParserService,
            LessonVideoParserService,
            ChallengeParserService,
            ChallengeV2ParserService,
            QuizDeckParserService,
            PathResolverService,
            UpsertService,
            CourseInsertService,
            ModuleInsertService,
            ContentInsertService,
            LessonVideoInsertService,
            ChallengeInsertService,
            ChallengeV2InsertService,
            QuizDeckInsertService,
            MilestoneIdFactoryService,
            MilestoneTaskIdFactoryService,
            MilestoneTaskPassCriteriaIdFactoryService,
            MilestoneTaskCodeImplementationIdFactoryService,
            MilestonePathService,
            MilestoneTaskPathService,
            MilestoneParserService,
            MilestoneTaskParserService,
            MilestoneInsertService,
            MilestoneTaskInsertService,
            MindMapParserService,
            MindMapInsertService,
            CourseSeederService,
            SeedersService,
            TemplateCvPathService,
            TemplateCvIdFactoryService,
            TemplateCvParserService,
            TemplateCvInsertService,
            CvSeederService,
            FoundationCategoryPathService,
            FoundationPathService,
            FoundationCategoryIdFactoryService,
            FoundationIdFactoryService,
            FoundationTagIdFactoryService,
            FoundationCategoryParserService,
            FoundationParserService,
            FoundationTagParserService,
            FoundationCategoryInsertService,
            FoundationInsertService,
            FoundationSeederService,
            HeadhuntingCompanyPathService,
            ConsultantPathService,
            HeadhuntingCompanyIdFactoryService,
            ConsultantIdFactoryService,
            HeadhuntingCompanyParserService,
            ConsultantParserService,
            HeadhuntingCompanyInsertService,
            ConsultantInsertService,
            HeadhuntingSeederService,
            AiModelCatalogPathService,
            SubscriptionCatalogPathService,
            AiModelCatalogParserService,
            SubscriptionCatalogParserService,
            AiModelInsertService,
            CatalogSeederService,
            CodingProblemPathService,
            CodingProblemParserService,
            CodingProblemInsertService,
            CodingProblemSeederService,
        ]
        
        return {
            ...dynamicModule,
            providers: [
                ...(dynamicModule.providers ?? []),
                ...providers,
            ],
            exports: providers,
        }
    }
}
