import {
    DynamicModule,
    Module,
} from "@nestjs/common"
import {
    ChallengeIdFactoryService,
    ChallengeSubmissionPromptIdFactoryService,
    ChallengeSubmissionCriteriaIdFactoryService,
    ChallengeSubmissionIdFactoryService,
    ChallengeRequirementIdFactoryService,
    ChallengeStepIdFactoryService,
    ChallengeOutputIdFactoryService,
    ChallengePrerequisiteIdFactoryService,
    ContentIdFactoryService,
    CodeExplainingIdFactoryService,
    CodeImplementationIdFactoryService,
    ContentBodyIdFactoryService,
    ContentLearningOutcomeIdFactoryService,
    CourseIdFactoryService,
    LivestreamSessionIdFactoryService,
    ModuleIdFactoryService,
    PrerequisiteIdFactoryService,
    PreviewContentIdFactoryService,
    PricingPhaseIdFactoryService,
    QnaIdFactoryService,
    ValuePropositionIdFactoryService,
    ChallengeParserService,
    FlashcardDeckParserService,
    PlaygroundParserService,
    PlaygroundStepParserService,
    MockInterviewParserService,
    ContentParserService,
    ContentLegacyParserService,
    CourseParserService,
    ModuleParserService,
    ChallengePathService,
    FlashcardDeckPathService,
    FlashcardDeckIdFactoryService,
    FlashcardCardIdFactoryService,
    PlaygroundPathService,
    PlaygroundStepPathService,
    PlaygroundIdFactoryService,
    PlaygroundStepIdFactoryService,
    MockInterviewPathService,
    MockInterviewIdFactoryService,
    MockInterviewLangIdFactoryService,
    MockInterviewChecklistIdFactoryService,
    MilestoneIdFactoryService,
    MilestoneTaskIdFactoryService,
    MilestoneTaskPassCriteriaIdFactoryService,
    MilestoneTaskCodeImplementationIdFactoryService,
    MilestoneTaskBriefIdFactoryService,
    MilestoneTaskOutcomeCriteriaIdFactoryService,
    MilestoneTaskOutcomeCriteriaLangIdFactoryService,
    MilestoneTaskApproachCriteriaIdFactoryService,
    MilestoneTaskApproachCriteriaLangIdFactoryService,
    MilestonePathService,
    MilestoneTaskPathService,
    MilestoneParserService,
    MilestoneTaskParserService,
    CourseSeederService,
    ContentPathService,
    CoursePathService,
    ModulePathService,
} from "./courses"
import {
    UuidPartitionPersistProcessorService,
    ChallengeProcessorService,
    ContentProcessorService,
    ModuleProcessorService,
    FlashcardDeckProcessorService,
    PlaygroundProcessorService,
    MockInterviewProcessorService,
    MilestoneTaskProcessorService,
    MilestoneProcessorService,
    CourseProcessorService,
} from "./courses/processors"
import {
    CvSeederService,
    TemplateCvIdFactoryService,
    TemplateCvInsertService,
    TemplateCvParserService,
    TemplateCvPathService,
} from "./cv"
import {
    FoundationSeederService,
    FoundationCategoryPathService,
    FoundationPathService,
    FoundationCategoryIdFactoryService,
    FoundationIdFactoryService,
    FoundationTagIdFactoryService,
    FoundationCategoryParserService,
    FoundationParserService,
    FoundationTagParserService,
    FoundationCategoryInsertService,
    FoundationInsertService,
} from "./foundations"
import {
    CatalogSeederService,
    AiModelCatalogPathService,
    SubscriptionCatalogPathService,
    AiModelCatalogParserService,
    SubscriptionCatalogParserService,
    AiModelInsertService,
} from "./catalog"
import {
    HeadhuntingSeederService,
    HeadhuntingCompanyPathService,
    ConsultantPathService,
    HeadhuntingCompanyIdFactoryService,
    ConsultantIdFactoryService,
    HeadhuntingCompanyParserService,
    ConsultantParserService,
    HeadhuntingCompanyInsertService,
    ConsultantInsertService,
} from "./headhuntings"
import {
    CodingProblemSeederService,
    CodingProblemPathService,
    CodingProblemParserService,
    CodingProblemInsertService,
    CodingProblemHintIndexService,
} from "./coding-problems"
import {
    AdvertisementSeederService,
} from "./advertisements"
import {
    ChangelogSeederService,
} from "./changelog"
import {
    BlogSeederService,
} from "./blog"
import {
    AchievementSeederService,
} from "./achievements"
import {
    InterviewQuestionEqIdFactoryService,
    InterviewQuestionEqParserService,
    InterviewQuestionEqPathService,
    MockInterviewEqSeederService,
} from "./mock-interview-eq"
import {
    SeedersService,
} from "./seeders.service"
import {
    ConfigurableModuleClass, OPTIONS_TYPE 
} from "./seeders.module-definition"
import {
    ExtractJsonFromMdService,
    CoerceMdScalarService,
    MergeJsonService,
    S3ContextService,
    FilesystemContextService,
    ContextLoaderService,
    PathResolverService,
    UpsertService,
    InterviewQuestionFieldsService,
} from "./shared"


/**
 * Module for the Seeders.
 * Provides all parser services and the SeedersService.
 */
@Module({
})
export class SeedersModule extends ConfigurableModuleClass {
    static register(
        options: typeof OPTIONS_TYPE
    ): DynamicModule {
        const dynamicModule = super.register(options)
        const providers = [
            ExtractJsonFromMdService,
            CoerceMdScalarService,
            MergeJsonService,
            S3ContextService,
            FilesystemContextService,
            ContextLoaderService,
            InterviewQuestionFieldsService,
            CourseIdFactoryService,
            ModuleIdFactoryService,
            ContentIdFactoryService,
            CodeExplainingIdFactoryService,
            CodeImplementationIdFactoryService,
            ContentBodyIdFactoryService,
            ContentLearningOutcomeIdFactoryService,
            PreviewContentIdFactoryService,
            PricingPhaseIdFactoryService,
            ValuePropositionIdFactoryService,
            PrerequisiteIdFactoryService,
            QnaIdFactoryService,
            LivestreamSessionIdFactoryService,
            CoursePathService,
            ModulePathService,
            ContentPathService,
            ChallengePathService,
            FlashcardDeckPathService,
            FlashcardDeckIdFactoryService,
            FlashcardCardIdFactoryService,
            PlaygroundPathService,
            PlaygroundStepPathService,
            PlaygroundIdFactoryService,
            PlaygroundStepIdFactoryService,
            MockInterviewPathService,
            MockInterviewIdFactoryService,
            MockInterviewLangIdFactoryService,
            MockInterviewChecklistIdFactoryService,
            ChallengeIdFactoryService,
            ChallengeSubmissionIdFactoryService,
            ChallengeSubmissionPromptIdFactoryService,
            ChallengeSubmissionCriteriaIdFactoryService,
            ChallengeRequirementIdFactoryService,
            ChallengeStepIdFactoryService,
            ChallengeOutputIdFactoryService,
            ChallengePrerequisiteIdFactoryService,
            CourseParserService,
            ModuleParserService,
            ContentParserService,
            ContentLegacyParserService,
            ChallengeParserService,
            FlashcardDeckParserService,
            PlaygroundParserService,
            PlaygroundStepParserService,
            MockInterviewParserService,
            PathResolverService,
            UpsertService,
            MilestoneIdFactoryService,
            MilestoneTaskIdFactoryService,
            MilestoneTaskPassCriteriaIdFactoryService,
            MilestoneTaskCodeImplementationIdFactoryService,
            MilestoneTaskBriefIdFactoryService,
            MilestoneTaskOutcomeCriteriaIdFactoryService,
            MilestoneTaskOutcomeCriteriaLangIdFactoryService,
            MilestoneTaskApproachCriteriaIdFactoryService,
            MilestoneTaskApproachCriteriaLangIdFactoryService,
            MilestonePathService,
            MilestoneTaskPathService,
            MilestoneParserService,
            MilestoneTaskParserService,
            UuidPartitionPersistProcessorService,
            ChallengeProcessorService,
            ContentProcessorService,
            ModuleProcessorService,
            FlashcardDeckProcessorService,
            PlaygroundProcessorService,
            MockInterviewProcessorService,
            MilestoneTaskProcessorService,
            MilestoneProcessorService,
            CourseProcessorService,
            CourseSeederService,
            AdvertisementSeederService,
            ChangelogSeederService,
            BlogSeederService,
            AchievementSeederService,
            InterviewQuestionEqPathService,
            InterviewQuestionEqIdFactoryService,
            InterviewQuestionEqParserService,
            MockInterviewEqSeederService,
            SeedersService,
            TemplateCvPathService,
            TemplateCvIdFactoryService,
            TemplateCvParserService,
            TemplateCvInsertService,
            CvSeederService,
            FoundationCategoryPathService,
            FoundationPathService,
            FoundationCategoryIdFactoryService,
            FoundationIdFactoryService,
            FoundationTagIdFactoryService,
            FoundationCategoryParserService,
            FoundationParserService,
            FoundationTagParserService,
            FoundationCategoryInsertService,
            FoundationInsertService,
            FoundationSeederService,
            HeadhuntingCompanyPathService,
            ConsultantPathService,
            HeadhuntingCompanyIdFactoryService,
            ConsultantIdFactoryService,
            HeadhuntingCompanyParserService,
            ConsultantParserService,
            HeadhuntingCompanyInsertService,
            ConsultantInsertService,
            HeadhuntingSeederService,
            AiModelCatalogPathService,
            SubscriptionCatalogPathService,
            AiModelCatalogParserService,
            SubscriptionCatalogParserService,
            AiModelInsertService,
            CatalogSeederService,
            CodingProblemPathService,
            CodingProblemParserService,
            CodingProblemInsertService,
            CodingProblemHintIndexService,
            CodingProblemSeederService,
        ]
        
        return {
            ...dynamicModule,
            providers: [
                ...(dynamicModule.providers ?? []),
                ...providers,
            ],
            exports: providers,
        }
    }
}
