#!/usr/bin/env node
/**
 * scripts/sync.mjs -- one-command dev sync for starci-academy-backend.
 *
 * Cross-platform (Windows, macOS, Linux/CI), node builtins only, no
 * dependencies -- so it runs before `npm ci` and before anything is built.
 *
 *   npm run sync                        decrypt, generate the env bridge, sync gitmounts
 *   npm run sync -- --out <path>        write the env bridge somewhere harmless
 *   npm run sync -- --write-override    force-write the live .env.override (CUTOVER)
 *   npm run sync -- --quiet             near-silent, never fatal (the prestart hook)
 *   npm run sync -- --help              this text
 *
 * What it does, in order:
 *   1. read metadata.json                 (single source of truth for every port)
 *   2. locate the shared master age key   (~/.starci/master.identity)
 *   3. check `sops` + `age` are on PATH
 *   4. sops-decrypt every .stacks/dev/**\/*.enc to the plaintext twin beside it
 *   5. GENERATE the env bridge            <-- the step that makes a fresh box boot
 *   6. clone/pull every gitmount declared in metadata.json
 *   7. create empty placeholders for the mount files boot would ENOENT on
 *   8. cross-check .stacks/dev/runtime/env/KEYS.md against what was produced
 *   9. print the resolved ports and the next commands
 *
 * Why step 5 matters: `src/modules/platform/env/config.ts` defaults point at
 * STANDARD ports (postgres 5432, redis 6379, qdrant 6333) and at the legacy
 * `.mount/` tree, while the compose fragments publish OFFSET ports and the
 * credentials now live under `.stacks/dev/runtime`. The generated override is
 * the bridge. It is gitignored and nothing ships it, so without this script a
 * fresh clone boots straight into ECONNREFUSED (or ENOENT).
 *
 * WHERE IT WRITES -- read this before running it on a live machine:
 *   - `.env.override` does not exist            -> writes `.env.override` (fresh clone)
 *   - `.env.override` starts with our marker    -> rewrites `.env.override` (already ours)
 *   - `.env.override` is hand-written / legacy  -> writes `.env.override.generated`
 *                                                  and does NOT touch the live file
 * That last case is today's state: the running backend keeps its working file
 * until the operator promotes the preview deliberately (see PROMOTION below).
 *
 * PROMOTION (the cutover, done once, by a human or the orchestrator):
 *   1. npm run sync                      -> writes .env.override.generated
 *   2. diff it against .env.override BY KEY NAME and eyeball the result
 *   3. stop the old stack, bring the new one up (npm run compose)
 *   4. npm run sync -- --write-override  -> backs the old file up to
 *                                           .env.override.bak, then writes the real one
 *   5. boot, verify, then delete the .bak (it still holds plaintext credentials)
 *
 * Every credential -- infra password and third-party key alike -- is written as
 * a `<KEY>_FILE` pointer, never as a value: config.ts reads each of them through
 * `parseEnvSecret`, which opens the file itself. The env bridge therefore holds
 * paths and ports, and no secret survives in it.
 *
 * This script NEVER prints a secret value. It prints key NAMES and ports only.
 */

import {
    copyFileSync,
    existsSync,
    mkdirSync,
    readdirSync,
    readFileSync,
    writeFileSync,
} from "node:fs"
import {
    basename,
    delimiter,
    dirname,
    join,
    relative,
    resolve,
    sep,
} from "node:path"
import {
    homedir,
    platform,
} from "node:os"
import {
    spawnSync,
} from "node:child_process"
import {
    fileURLToPath,
    pathToFileURL,
} from "node:url"

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)),
    "..")
const IS_WINDOWS = platform() === "win32"

/** Marker written as the first line of a generated env bridge. */
const GENERATED_MARKER = "# GENERATED BY scripts/sync.mjs"

/** Relative paths this script reads or writes. */
const PATHS = {
    metadata: join(REPO_ROOT,
        "metadata.json"),
    config: join(REPO_ROOT,
        "src",
        "modules",
        "platform",
        "env",
        "config.ts"),
    credentials: join(REPO_ROOT,
        "scripts",
        "credentials.mjs"),
    stacksDev: join(REPO_ROOT,
        ".stacks",
        "dev"),
    // KEY=VALUE files only. `runtime/files` holds whole-file credentials that are
    // decrypted to disk and referenced BY PATH, never folded into env vars.
    stacksDevRuntimeEnv: join(REPO_ROOT,
        ".stacks",
        "dev",
        "runtime",
        "env"),
    stacksDevRuntimeFiles: join(REPO_ROOT,
        ".stacks",
        "dev",
        "runtime",
        "files"),
    stacksDevRuntimeConfig: join(REPO_ROOT,
        ".stacks",
        "dev",
        "runtime",
        "config"),
    seedTemplate: join(REPO_ROOT,
        "config",
        "seed.example.yaml"),
    envOverride: join(REPO_ROOT,
        ".env.override"),
    envPreview: join(REPO_ROOT,
        ".env.override.generated"),
    envOverrideBackup: join(REPO_ROOT,
        ".env.override.bak"),
    // NOTE: no gitmounts path here on purpose. Which repos are mounted, at which
    // ref, and where they land is declared in metadata.json under "gitmounts",
    // so adding a second source is one line of JSON, not an edit to this script.
}

const MASTER_KEY_PATH = join(homedir(),
    ".starci",
    "master.identity")

/**
 * Repo-relative POSIX prefixes the generated env bridge points mount paths at.
 * Forward slashes on purpose: the value ends up in a dotenv file read on Windows
 * and Linux alike, and node resolves `/` fine on both.
 */
const RUNTIME_FILES_PREFIX = ".stacks/dev/runtime/files"
const RUNTIME_CONFIG_PREFIX = ".stacks/dev/runtime/config"

// ---------------------------------------------------------------------------
// output helpers
// ---------------------------------------------------------------------------

const USE_COLOR = Boolean(process.stdout.isTTY) && !process.env.NO_COLOR
const paint = (code, text) => USE_COLOR
    ? `[${code}m${text}[0m`
    : text
const cyan = (text) => paint("36",
    text)
const green = (text) => paint("32",
    text)
const yellow = (text) => paint("33",
    text)
const red = (text) => paint("31",
    text)
const dim = (text) => paint("2",
    text)

let stepNumber = 0

/**
 * Quiet mode. Set by `--quiet`, which is how the npm `prestart` hooks run this
 * script before every `npm run start:dev`. There it must be near-silent, must
 * never touch the network, and must NEVER be fatal -- a machine without sops
 * installed still has to be able to start the dev server it started yesterday.
 */
let QUIET = false

/** Prints a numbered step header. */
const step = (title) => {
    stepNumber += 1
    if (!QUIET) {
        console.log(`\n${cyan(`==> ${stepNumber}. ${title}`)}`)
    }
}

const info = (message) => {
    if (!QUIET) {
        console.log(`    ${message}`)
    }
}
const note = (message) => {
    if (!QUIET) {
        console.log(`    ${dim(message)}`)
    }
}
const ok = (message) => {
    if (!QUIET) {
        console.log(`    ${green("ok")}   ${message}`)
    }
}
const warn = (message) => console.log(`    ${yellow("warn")} ${message}`)

/**
 * Aborts with a readable, actionable message instead of a stack trace.
 *
 * Under `--quiet` it does NOT abort: it prints one warning line and exits 0.
 * The prestart hook must never be the reason `npm run start:dev` fails.
 * @param title - one-line statement of what went wrong.
 * @param remedy - lines telling the operator exactly what to do next.
 */
const fail = (title, remedy = []) => {
    if (QUIET) {
        console.log(`    ${yellow("warn")} sync skipped: ${title}`)
        console.log(`    ${dim("run `npm run sync` for the full explanation")}`)
        process.exit(0)
    }
    console.error(`\n${red(`FAILED: ${title}`)}`)
    for (const line of remedy) {
        console.error(`    ${line}`)
    }
    console.error("")
    process.exit(1)
}

// ---------------------------------------------------------------------------
// process helpers
// ---------------------------------------------------------------------------

/**
 * Resolves an executable against PATH by hand. `spawnSync` without a shell does
 * not honour PATHEXT on Windows, so `sops`/`age`/`git` would look "missing"
 * there even when installed. Resolving to an absolute path keeps `shell: false`
 * (no quoting hazards) while still finding `.exe` / `.cmd` shims.
 * @param command - bare command name, e.g. "sops".
 * @returns absolute path to the executable, or null when not found.
 */
const resolveCommand = (command) => {
    const searchDirs = (process.env.PATH || "").split(delimiter).filter(Boolean)
    if (IS_WINDOWS && process.env.LOCALAPPDATA) {
        // winget puts its shims here and the PATH entry only lands in NEW shells
        const wingetRoot = join(process.env.LOCALAPPDATA,
            "Microsoft",
            "WinGet")
        searchDirs.push(join(wingetRoot,
            "Links"))
        // Not every package gets a Links shim -- age and sops both install as a
        // bare exe under Packages/<id>/ (sometimes one level deeper) and rely on
        // a PATH entry this process is too old to have seen. Walk it directly.
        const packagesRoot = join(wingetRoot,
            "Packages")
        if (existsSync(packagesRoot)) {
            for (const entry of readdirSync(packagesRoot)) {
                const packageDir = join(packagesRoot,
                    entry)
                searchDirs.push(packageDir)
                try {
                    for (const nested of readdirSync(packageDir,
                        {
                            withFileTypes: true
                        })) {
                        if (nested.isDirectory()) {
                            searchDirs.push(join(packageDir,
                                nested.name))
                        }
                    }
                } catch {
                    // unreadable package dir -- skip, another candidate may match
                }
            }
        }
    }
    const extensions = IS_WINDOWS
        ? (process.env.PATHEXT || ".EXE;.CMD;.BAT").split(";").filter(Boolean)
        : [""]
    for (const dir of searchDirs) {
        for (const extension of extensions) {
            const candidate = join(dir,
                `${command}${extension}`)
            if (existsSync(candidate)) {
                return candidate
            }
        }
    }
    return null
}

/**
 * Runs a command and returns its result. Never throws.
 * @param command - bare command name (resolved via resolveCommand).
 * @param args - argument list.
 * @param options - `{ cwd, env, capture }`; `capture: false` inherits stdio.
 */
const run = (command, args, options = {
}) => {
    const executable = resolveCommand(command)
    if (!executable) {
        return {
            found: false, status: -1, stdout: "", stderr: ""
        }
    }
    const result = spawnSync(executable,
        args,
        {
            cwd: options.cwd ?? REPO_ROOT,
            env: options.env ?? process.env,
            encoding: "utf8",
            stdio: options.capture === false ? "inherit" : "pipe",
        })
    return {
        found: true,
        status: result.status ?? -1,
        stdout: result.stdout ?? "",
        stderr: result.stderr ?? "",
    }
}

// ---------------------------------------------------------------------------
// env-file helpers
// ---------------------------------------------------------------------------

/**
 * Parses a dotenv-style file body into a plain object. Deliberately small: the
 * app itself parses these with @nestjs/config, this only needs enough to merge.
 * @param body - raw file contents.
 */
const parseEnvBody = (body) => {
    const entries = {
    }
    for (const rawLine of body.split(/\r?\n/)) {
        const line = rawLine.trim()
        if (!line || line.startsWith("#")) {
            continue
        }
        const withoutExport = line.startsWith("export ")
            ? line.slice("export ".length)
            : line
        const separator = withoutExport.indexOf("=")
        if (separator <= 0) {
            continue
        }
        const key = withoutExport.slice(0,
            separator).trim()
        let value = withoutExport.slice(separator + 1).trim()
        const quoted = (value.startsWith("\"") && value.endsWith("\"") && value.length > 1)
            || (value.startsWith("'") && value.endsWith("'") && value.length > 1)
        if (quoted) {
            value = value.slice(1,
                -1)
        }
        entries[key] = value
    }
    return entries
}

/**
 * Quotes a value only when it would otherwise be misread (whitespace, `#`, or a
 * quote character). Everything else stays bare so diffs remain readable.
 * @param value - the value to serialise.
 */
const formatEnvValue = (value) => {
    const text = String(value)
    if (text === "") {
        return ""
    }
    if (/[\s#"']/.test(text)) {
        return `"${text.replace(/\\/g,
            "\\\\").replace(/"/g,
            "\\\"")}"`
    }
    return text
}

// ---------------------------------------------------------------------------
// credentials table (written by scripts/credentials.mjs)
// ---------------------------------------------------------------------------

/**
 * Loads the credential table if it exists. It is a sibling script, not a
 * dependency: sync still runs (and still writes every port) on a checkout where
 * the table has not landed yet, it just cannot fill in generated passwords.
 * @returns `{ CREDENTIALS, REDIS_LANE_ALIASES, DERIVED_CREDENTIALS, APP_CREDENTIALS }`, all defaulted.
 */
const loadCredentialTable = async () => {
    const empty = {
        CREDENTIALS: [],
        REDIS_LANE_ALIASES: [],
        DERIVED_CREDENTIALS: [],
        APP_CREDENTIALS: [],
    }
    if (!existsSync(PATHS.credentials)) {
        return empty
    }
    try {
        const module = await import(pathToFileURL(PATHS.credentials).href)
        return {
            CREDENTIALS: Array.isArray(module.CREDENTIALS)
                ? module.CREDENTIALS
                : [],
            REDIS_LANE_ALIASES: Array.isArray(module.REDIS_LANE_ALIASES)
                ? module.REDIS_LANE_ALIASES
                : [],
            DERIVED_CREDENTIALS: Array.isArray(module.DERIVED_CREDENTIALS)
                ? module.DERIVED_CREDENTIALS
                : [],
            APP_CREDENTIALS: Array.isArray(module.APP_CREDENTIALS)
                ? module.APP_CREDENTIALS
                : [],
        }
    } catch (error) {
        warn(`scripts/credentials.mjs could not be loaded: ${error.message}`)
        return empty
    }
}

/**
 * Resolves every credential to the FILE it lives in, keyed by the env var it
 * feeds. No value ever leaves this function: config.ts reads secrets through
 * `parseEnvSecret`, so the bridge carries `<KEY>_FILE` pointers and the app
 * opens the file itself. The file is still read here, but only to prove it
 * exists and is non-empty -- a pointer to an empty file fails the boot.
 * @param table - the loaded credential table.
 * @returns `{ pointers: Map<string,string>, missing: string[] }` -- names and paths only.
 */
const readCredentialValues = (table) => {
    const pointers = new Map()
    const missing = []
    const rows = [...table.CREDENTIALS,
        ...table.DERIVED_CREDENTIALS,
        ...table.APP_CREDENTIALS]
    for (const credential of rows) {
        if (!credential
            || typeof credential.env !== "string"
            || typeof credential.file !== "string") {
            continue
        }
        const source = join(PATHS.stacksDevRuntimeFiles,
            credential.file)
        if (!existsSync(source)) {
            missing.push(credential.env)
            continue
        }
        const raw = readFileSync(source,
            "utf8").trim()
        if (raw === "") {
            missing.push(credential.env)
            continue
        }
        // repo-relative POSIX path: the app resolves it against process.cwd()
        const pointer = `${RUNTIME_FILES_PREFIX}/${credential.file}`
        pointers.set(credential.env,
            pointer)
        // one redis server, four logical lanes -- they share the one password file
        if (credential.env.startsWith("REDIS_")) {
            for (const alias of table.REDIS_LANE_ALIASES) {
                pointers.set(alias,
                    pointer)
            }
        }
    }
    return {
        pointers, missing
    }
}

// ---------------------------------------------------------------------------
// step 1 -- metadata.json
// ---------------------------------------------------------------------------

/** Port names this script refuses to run without. */
const REQUIRED_PORTS = ["core",
    "postgres",
    "redis",
    "elasticsearch",
    "qdrant",
    "kafka",
    "minio",
    "nats",
    "keycloak",
    "prometheus"]

/**
 * Reads metadata.json as-is, without the port validation `readMetadata` does.
 * Used by the gitmounts step, which needs a different part of the same file.
 * @returns the parsed object, or `{}` when the file is unreadable.
 */
const readMetadataRaw = () => {
    try {
        return JSON.parse(readFileSync(PATHS.metadata,
            "utf8"))
    } catch {
        return {
        }
    }
}

/**
 * Reads metadata.json and returns the resolved port map. Every port used
 * anywhere below comes from here -- nothing in this script hardcodes one.
 */
const readMetadata = () => {
    step("metadata.json (port source of truth)")
    if (!existsSync(PATHS.metadata)) {
        fail("metadata.json is missing at the repo root.",
            [`expected: ${PATHS.metadata}`,
                "It declares \"portOffset\" and the resolved \"ports\" map that every",
                "other file (compose fragments, the env bridge) derives from.",
                "Restore it from git."])
    }
    let metadata
    try {
        metadata = JSON.parse(readFileSync(PATHS.metadata,
            "utf8"))
    } catch (error) {
        fail("metadata.json is not valid JSON.",
            [`file:  ${PATHS.metadata}`,
                `error: ${error.message}`])
    }
    const ports = metadata.ports ?? {
    }
    const basePorts = metadata.basePorts ?? {
    }
    const offset = metadata.portOffset

    const missing = REQUIRED_PORTS.filter((name) => typeof ports[name] !== "number")
    if (missing.length > 0) {
        fail("metadata.json is missing required ports.",
            [`missing: ${missing.join(", ")}`,
                "Add them under \"ports\" as basePort + portOffset."])
    }
    if (typeof offset === "number") {
        for (const [name, port] of Object.entries(ports)) {
            const base = basePorts[name]
            if (typeof base === "number" && base + offset !== port) {
                warn(`ports.${name} (${port}) != basePorts.${name} + portOffset (${base + offset})`)
            }
        }
    }
    ok(`project "${metadata.project ?? "unknown"}", portOffset ${offset ?? "n/a"}, ${Object.keys(ports).length} ports`)
    return {
        metadata, ports, offset
    }
}

// ---------------------------------------------------------------------------
// step 2 -- master key
// ---------------------------------------------------------------------------

/** Verifies the shared master age key exists; that key is never in the repo or CI. */
const locateMasterKey = () => {
    step("master key")
    if (!existsSync(MASTER_KEY_PATH)) {
        fail("the shared master age key is missing on this machine.",
            [`expected at: ${MASTER_KEY_PATH}`,
                "",
                "This one key is shared across every project of this owner and is NEVER",
                "committed and NEVER uploaded to CI (CI uses GitHub Actions secrets).",
                "Get it out-of-band, then re-run `npm run sync`:",
                "",
                "  - copy it from another machine that already has it, or",
                "  - pull it from the password manager entry that holds it",
                "",
                IS_WINDOWS
                    ? "  mkdir %USERPROFILE%\\.starci   and drop master.identity inside"
                    : "  mkdir -p ~/.starci && chmod 700 ~/.starci   and drop master.identity inside"])
    }
    ok(`present at ${MASTER_KEY_PATH}`)
    return MASTER_KEY_PATH
}

// ---------------------------------------------------------------------------
// step 3 -- sops + age
// ---------------------------------------------------------------------------

/** Per-platform install hints. Nothing is ever installed silently. */
const INSTALL_HINTS = {
    sops: {
        win32: "winget install Mozilla.SOPS",
        darwin: "brew install sops",
        linux: "curl -sSLo sops https://github.com/getsops/sops/releases/latest/download/sops-linux-amd64 && sudo install -m 0755 sops /usr/local/bin/sops",
    },
    age: {
        win32: "winget install FiloSottile.age",
        darwin: "brew install age",
        linux: "sudo apt-get install -y age",
    },
}

/** Fails unless both `sops` and `age` are callable. */
const ensureTools = () => {
    step("sops + age")
    const current = platform()
    const missing = ["sops",
        "age"].filter((tool) => resolveCommand(tool) === null)
    if (missing.length > 0) {
        const width = Math.max(...missing.map((tool) => tool.length))
        const hints = missing.map((tool) => {
            const hint = INSTALL_HINTS[tool][current] ?? INSTALL_HINTS[tool].linux
            return `  ${`${tool}:`.padEnd(width + 2)} ${hint}`
        })
        fail(`missing on PATH: ${missing.join(", ")}`,
            ["Install, open a NEW shell so PATH is picked up, then re-run `npm run sync`.",
                "",
                ...hints,
                "",
                "Nothing is installed for you on purpose -- these tools hold the keys to",
                "every secret in the repo, so you choose where they come from."])
    }
    const sopsVersion = run("sops",
        ["--version"]).stdout.trim().split(/\r?\n/)[0]
    ok(`sops (${sopsVersion || "version unknown"}) and age both on PATH`)
}

// ---------------------------------------------------------------------------
// step 4 -- decrypt .stacks/dev
// ---------------------------------------------------------------------------

/**
 * Walks a directory tree and returns every `*.enc` file in it.
 * @param root - directory to walk; a missing directory yields nothing.
 * @returns absolute paths, sorted so output is stable between runs.
 */
const findEncryptedFiles = (root) => {
    if (!existsSync(root)) {
        return []
    }
    const found = []
    const walk = (dir) => {
        for (const entry of readdirSync(dir,
            {
                withFileTypes: true
            })) {
            const full = join(dir,
                entry.name)
            if (entry.isDirectory()) {
                walk(full)
            } else if (entry.name.endsWith(".enc")) {
                found.push(full)
            }
        }
    }
    walk(root)
    return found.sort()
}

/**
 * Picks the sops format for a file. `.env` files are dotenv; whole-file
 * credentials (api keys, tokens, service-account json) are opaque and must be
 * binary, or sops tries to parse a bare token as JSON and dies.
 * @param plaintextPath - the path without the `.enc` suffix.
 */
const sopsFormatFor = (plaintextPath) => {
    if (plaintextPath.endsWith(".env")) {
        return "dotenv"
    }
    // Never let sops infer. The file it is handed ends in `.enc`, so inference
    // falls back to binary and a JSON secret fails with "No binary data found
    // in tree" -- after encrypting perfectly well, which makes it look like the
    // key is wrong rather than the format.
    if (/\.json$/.test(plaintextPath)) {
        return "json"
    }
    if (/\.ya?ml$/.test(plaintextPath)) {
        return "yaml"
    }
    return "binary"
}

/**
 * Decrypts the whole `dev` stack -- `runtime/env` (folded into the env bridge)
 * and `runtime/files` (whole-file credentials the app reads by path). Only `dev`
 * keeps values on disk: `vps` reads GitHub Actions secrets and `k8s` will read a
 * cloud secret manager, so both are markdown-only scaffolds.
 * @param masterKeyPath - absolute path to the age key sops decrypts with.
 * @returns the decrypted plaintext paths that were produced.
 */
const decryptDevStack = (masterKeyPath) => {
    step("decrypt .stacks/dev")
    if (!existsSync(PATHS.stacksDev)) {
        note(".stacks/dev does not exist yet -- skipping decryption.")
        note("(the env bridge below is still generated from metadata.json)")
        return []
    }
    const encrypted = findEncryptedFiles(PATHS.stacksDev)
    if (encrypted.length === 0) {
        note("no *.enc files found -- nothing to decrypt.")
        return []
    }
    const sopsEnv = {
        ...process.env, SOPS_AGE_KEY_FILE: masterKeyPath
    }
    const produced = []
    for (const source of encrypted) {
        const target = source.replace(/\.enc$/,
            "")
        // The types must be stated. sops infers format from the extension, and
        // `.enc` means nothing to it, so it falls back to JSON and dies on the
        // first comment line: "invalid character '#' looking for beginning of
        // value". Likewise always use --output, never shell redirection: on
        // Windows that writes CRLF and sops then fails to parse its own
        // timestamp ("extra text: \r").
        const format = sopsFormatFor(target)
        const result = run("sops",
            ["--decrypt",
                "--input-type",
                format,
                "--output-type",
                format,
                "--output",
                target,
                source],
            {
                env: sopsEnv
            })
        const label = relative(PATHS.stacksDev,
            source).split(sep).join("/")
        if (result.status !== 0) {
            fail(`sops could not decrypt ${label}`,
                [`sops exit code ${result.status}`,
                    result.stderr.trim().split(/\r?\n/).slice(-4)
                        .map((line) => `  ${line}`).join("\n"),
                    "",
                    "Usual causes:",
                    "  - the master key is not a recipient of this file (re-encrypt it), or",
                    "  - the file was encrypted with a different key.",
                    `key in use: ${masterKeyPath}`])
        }
        produced.push(target)
        ok(label.replace(/\.enc$/,
            ""))
    }
    return produced
}

// ---------------------------------------------------------------------------
// step 5 -- generate the env bridge
// ---------------------------------------------------------------------------

/**
 * Extracts every env key `src/modules/platform/env/config.ts` actually reads, so
 * this script can never emit a key the app ignores. Handles both literal keys
 * (`key: "CORE_PORT"`) and templated ones (`key: NATS_SERVER_${i + 1}_HOST`).
 * @returns `{ literal: Set<string>, patterns: RegExp[] }`
 */
const collectConfigKeys = () => {
    if (!existsSync(PATHS.config)) {
        fail("src/modules/platform/env/config.ts is missing.",
            [`expected: ${PATHS.config}`,
                "It is the only list of env keys the app reads; without it this script",
                "cannot tell a real key from a typo."])
    }
    const body = readFileSync(PATHS.config,
        "utf8")
    const literal = new Set()
    for (const match of body.matchAll(/key:\s*"([A-Za-z0-9_.]+)"/g)) {
        literal.add(match[1])
    }
    const patterns = []
    for (const match of body.matchAll(/key:\s*`([^`]+)`/g)) {
        // every templated family in config.ts is indexed by a number (`${i + 1}`),
        // so the placeholder becomes \d+ -- narrow on purpose, otherwise the
        // doc placeholders in KEYS.md ("NATS_SERVER_N_HOST") read as real keys
        const source = match[1]
            .replace(/[.*+?^${}()|[\]\\]/g,
                "\\$&")
            .replace(/\\\$\\\{[^}]*\\\}/g,
                "\\d+")
        patterns.push(new RegExp(`^${source}$`))
    }
    return {
        literal, patterns
    }
}

/**
 * Finds every key in config.ts whose default is `join(process.cwd(), ...)` and
 * returns the literal path segments of that default.
 *
 * This is how the mount-path overrides stay honest: the relocation table below
 * is driven by what config.ts ACTUALLY declares, so a credential added to
 * config.ts later is picked up without editing this script.
 * @returns array of `{ key, segments }`.
 */
const collectMountPathDefaults = () => {
    const body = readFileSync(PATHS.config,
        "utf8")
    const found = []
    const keyPattern = /key:\s*"([A-Za-z0-9_.]+)"/g
    let match = keyPattern.exec(body)
    while (match !== null) {
        const key = match[1]
        // window starts AFTER this key so the scan below cannot borrow it
        const window = body.slice(match.index + match[0].length,
            match.index + match[0].length + 400)
        const joinAt = window.search(/defaultValue:\s*join\(/)
        // a `key:` between here and the join means the join belongs to the NEXT
        // entry, not this one -- skip rather than mis-attribute a path
        const stolen = joinAt !== -1 && /key:\s*["`]/.test(window.slice(0,
            joinAt))
        if (joinAt !== -1 && !stolen) {
            const openParen = window.indexOf("(",
                window.indexOf("join",
                    joinAt))
            // balance-scan to the matching ")" -- `process.cwd()` nests one level
            let depth = 0
            let end = -1
            for (let i = openParen; i < window.length; i += 1) {
                if (window[i] === "(") {
                    depth += 1
                } else if (window[i] === ")") {
                    depth -= 1
                    if (depth === 0) {
                        end = i
                        break
                    }
                }
            }
            if (end !== -1) {
                const argumentList = window.slice(openParen + 1,
                    end)
                const segments = [...argumentList.matchAll(/"([^"]*)"/g)]
                    .map((segment) => segment[1])
                if (segments.length > 0) {
                    found.push({
                        key, segments
                    })
                }
            }
        }
        match = keyPattern.exec(body)
    }
    return found
}

/**
 * Relocates one legacy `.mount/...` default onto the new tree.
 *
 *   .mount/terraform/<name>          -> .stacks/dev/runtime/files/<name>
 *   .mount/terraform/keys[/<name>]   -> .stacks/dev/runtime/files[/<name>]
 *   .mount/config/app.yaml           -> .stacks/dev/runtime/files/app.yaml
 *   .mount/config/seed.yaml          -> .stacks/dev/runtime/config/seed.yaml
 *   .mount/data/<rest...>            -> <gitmount path>/<rest...>
 *   .mount/assets                    -> <gitmount path>/assets
 *
 * The assets rule is not a guess. `.mount/assets` used to hold ten foundation
 * logos while the data repo carried the same ten under `assets/foundation`
 * alongside the achievement badges and course covers -- and AssetsService
 * uploads its whole root under the `assets/` object-key prefix, which is where
 * `assets/badges/achievements/*.png` has to come from. The mount was the cut-down
 * copy; the gitmount is the real root.
 *
 * Everything else is left alone on purpose:
 *   - `.mount/config/metadata.json` is i18n CONTENT rather than a secret. Note
 *     that nothing reads it: `CONFIG_METADATA_MOUNT_PATH` is declared in
 *     config.ts and consumed nowhere, so relocating it would move a dead file;
 *   - defaults that do not start at `.mount` (e.g. `.contexts`) are not ours.
 * @param segments - the literal path segments of the config.ts default.
 * @param dataMountPath - repo-relative POSIX path of the `data` gitmount.
 * @returns the replacement POSIX path, or null when the default stays as it is.
 */
const relocateMountPath = (segments, dataMountPath) => {
    if (segments[0] !== ".mount") {
        return null
    }
    const rest = segments.slice(1)
    if (rest[0] === "terraform") {
        // the AI key pools are flattened into runtime/files beside everything else
        const tail = rest[1] === "keys" ? rest.slice(2) : rest.slice(1)
        return [RUNTIME_FILES_PREFIX,
            ...tail].join("/")
    }
    if (rest[0] === "config") {
        if (rest[1] === "app.yaml") {
            return `${RUNTIME_FILES_PREFIX}/app.yaml`
        }
        if (rest[1] === "seed.yaml") {
            return `${RUNTIME_CONFIG_PREFIX}/seed.yaml`
        }
        return null
    }
    if (rest[0] === "data") {
        return [dataMountPath,
            ...rest.slice(1)].join("/")
    }
    if (rest[0] === "assets") {
        return [dataMountPath,
            ...rest].join("/")
    }
    return null
}

/**
 * Builds every key/value the env bridge should carry, grouped into commented
 * sections. Ports come from metadata.json; a `null` value marks a GENERATED
 * credential, whose value only ever comes from `.stacks/dev/runtime/files`.
 * @param ports - the resolved port map from metadata.json.
 */
const buildDerivedSections = (ports) => [
    {
        title: "Core API -- the port apps/core listens on (envConfig().services.core.port)",
        entries: [["CORE_PORT",
            ports.core],
        ["API_PORT",
            ports.core]],
    },
    {
        title: "PostgreSQL primary -- compose service `postgres`",
        entries: [["POSTGRESQL_PRIMARY_HOST",
            "localhost"],
        ["POSTGRESQL_PRIMARY_PORT",
            ports.postgres],
        // null, not "postgres": secret:gen MINTS the superuser name into
        // postgres-user.txt and compose initialises the volume with it, so a literal
        // here hands the app a role the server has never heard of -- which surfaces
        // as "password authentication failed", pointing at the wrong half of the pair.
        ["POSTGRESQL_PRIMARY_USERNAME",
            null],
        ["POSTGRESQL_PRIMARY_PASSWORD",
            null],
        ["POSTGRESQL_PRIMARY_DATABASE",
            "starci-academy"]],
    },
    {
        title: "Redis -- one compose service behind all four logical lanes",
        entries: ["BULLMQ",
            "CACHE",
            "THROTTLER",
            "ADAPTER"].flatMap((lane) => [
            [`REDIS_${lane}_HOST`,
                "localhost"],
            [`REDIS_${lane}_PORT`,
                ports.redis],
            [`REDIS_${lane}_PASSWORD`,
                null],
        ]),
    },
    {
        title: "Elasticsearch -- compose service `elasticsearch` (security on, no TLS in dev)",
        entries: [["ELASTICSEARCH_NODE",
            `http://localhost:${ports.elasticsearch}`],
        ["ELASTICSEARCH_USERNAME",
            "elastic"],
        ["ELASTICSEARCH_PASSWORD",
            null]],
    },
    {
        title: "Qdrant -- compose service `qdrant`, REST port",
        entries: [["QDRANT_URL",
            `http://localhost:${ports.qdrant}`],
        ["QDRANT_API_KEY",
            null]],
    },
    {
        title: "Kafka -- compose service `kafka` (KRaft), EXTERNAL listener",
        entries: [["KAFKA_BROKERS",
            `localhost:${ports.kafka}`]],
    },
    {
        title: "S3 / MinIO -- compose service `minio`; bucket created by minio-init",
        entries: [["S3_MINIO_ENDPOINT",
            `http://localhost:${ports.minio}`],
        ["S3_MINIO_PUBLIC_ENDPOINT",
            `http://localhost:${ports.minio}`],
        ["S3_MINIO_ACCESS_KEY_ID",
            null],
        ["S3_MINIO_SECRET_ACCESS_KEY",
            null],
        ["S3_MINIO_BUCKET",
            "starci-academy"]],
    },
    {
        title: "NATS -- compose runs `nats -js --auth <token>`; config.ts has no NATS_URL,"
            + "\n# it builds the server list from NATS_SERVER_<n>_HOST/PORT",
        entries: [["NATS_SERVERS_COUNT",
            1],
        ["NATS_SERVER_1_HOST",
            "localhost"],
        ["NATS_SERVER_1_PORT",
            ports.nats],
        ["NATS_AUTH_ENABLED",
            true],
        ["NATS_AUTH_TOKEN",
            null]],
    },
    {
        title: "Keycloak -- compose service `keycloak`, start-dev",
        entries: [["KEYCLOAK_URL",
            `http://localhost:${ports.keycloak}`],
        // null for the same reason as postgres: keycloak-admin-user.txt is minted and
        // the container is created with it. ELASTICSEARCH_USERNAME above stays literal
        // on purpose - `elastic` is the image's built-in superuser and there is no
        // minted file for it, so that one is a fact rather than an oversight.
        ["KEYCLOAK_ADMIN_USERNAME",
            null],
        ["KEYCLOAK_ADMIN_PASSWORD",
            null]],
    },
    {
        title: "Prometheus -- scrapes cAdvisor; the app queries it from the HOST",
        entries: [["PROMETHEUS_URL",
            `http://localhost:${ports.prometheus}`]],
    },
    {
        title: "OAuth callbacks -- served by THIS app, so they follow the core port",
        entries: [["KEYCLOAK_GOOGLE_REDIRECT_URI",
            `http://localhost:${ports.core}/api/v1/keycloak/google/callback`],
        ["KEYCLOAK_GITHUB_REDIRECT_URI",
            `http://localhost:${ports.core}/api/v1/keycloak/github/callback`],
        ["GITHUB_OAUTH_REDIRECT_URI",
            `http://localhost:${ports.core}/api/v1/github/oauth/callback`]],
    },
    {
        title: "App-level secrets minted into the stack (never a human's choice)",
        entries: [["CSRF_SECRET",
            null]],
    },
]

/**
 * Keys whose value is DERIVED from metadata.json. A decrypted `.env` may not
 * override these -- if it could, the port map would stop being single-source.
 */
const METADATA_OWNED_KEYS = new Set(["CORE_PORT",
    "API_PORT",
    "POSTGRESQL_PRIMARY_PORT",
    "REDIS_BULLMQ_PORT",
    "REDIS_CACHE_PORT",
    "REDIS_THROTTLER_PORT",
    "REDIS_ADAPTER_PORT",
    "ELASTICSEARCH_NODE",
    "QDRANT_URL",
    "KAFKA_BROKERS",
    "NATS_SERVER_1_PORT",
    "S3_MINIO_ENDPOINT",
    "S3_MINIO_PUBLIC_ENDPOINT",
    "KEYCLOAK_URL",
    "PROMETHEUS_URL",
    "KEYCLOAK_GOOGLE_REDIRECT_URI",
    "KEYCLOAK_GITHUB_REDIRECT_URI",
    "GITHUB_OAUTH_REDIRECT_URI"])

/**
 * Decides WHERE the env bridge is written, and why.
 *
 * The whole point of this function is that a normal `npm run sync` on a machine
 * whose `.env.override` was written by hand must not touch that file. See the
 * header block for the promotion sequence.
 * @param explicitOut - value of `--out`, or null.
 * @param forceOverride - true when `--write-override` was passed.
 */
const resolveTarget = (explicitOut, forceOverride) => {
    if (explicitOut) {
        return {
            path: resolve(REPO_ROOT,
                explicitOut),
            mode: "explicit",
        }
    }
    if (forceOverride) {
        return {
            path: PATHS.envOverride, mode: "forced"
        }
    }
    if (!existsSync(PATHS.envOverride)) {
        return {
            path: PATHS.envOverride, mode: "fresh"
        }
    }
    const head = readFileSync(PATHS.envOverride,
        "utf8").slice(0,
        GENERATED_MARKER.length)
    if (head === GENERATED_MARKER) {
        return {
            path: PATHS.envOverride, mode: "regenerate"
        }
    }
    return {
        path: PATHS.envPreview, mode: "preview"
    }
}

/**
 * Writes the env bridge -- the file that reconciles config.ts standard-port,
 * `.mount`-rooted defaults with the offset ports compose publishes and the
 * credentials that now live under `.stacks/dev/runtime`.
 * @param ports - resolved port map.
 * @param decryptedEnvFiles - plaintext `.env` paths produced by step 4.
 * @param credentials - `{ pointers, missing }` from readCredentialValues.
 * @param dataMountPath - repo-relative POSIX path of the `data` gitmount.
 * @param target - `{ path, mode }` from resolveTarget.
 * @returns `{ emitted: string[] }` -- names only, never values.
 */
const writeEnvBridge = (
    ports,
    decryptedEnvFiles,
    credentials,
    dataMountPath,
    target,
) => {
    step("generate the env bridge")
    const {
        literal, patterns
    } = collectConfigKeys()
    const isKnownKey = (key) => literal.has(key)
        || patterns.some((pattern) => pattern.test(key))
    note(`config.ts declares ${literal.size} literal keys + ${patterns.length} templated keys`)

    // decrypted env files first, so a real stored value beats the shaped default
    const fromSecrets = {
    }
    for (const file of decryptedEnvFiles) {
        Object.assign(fromSecrets,
            parseEnvBody(readFileSync(file,
                "utf8")))
    }
    if (decryptedEnvFiles.length > 0) {
        note(`merged ${Object.keys(fromSecrets).length} keys from ${decryptedEnvFiles.length} decrypted file(s)`)
    }

    const emitted = []
    const skipped = []
    const unfilled = []
    const usedFromSecrets = new Set()

    const lines = [`${GENERATED_MARKER} -- DO NOT EDIT BY HAND`,
        "#",
        "# Every edit here is overwritten by the next `npm run sync`. Change the source",
        "# instead:",
        "#   ports        -> metadata.json  (host port = basePort + portOffset)",
        "#   credentials  -> .stacks/dev/runtime/**  (sops, then `npm run sync`)",
        "#",
        "# Why this file exists: src/modules/platform/env/config.ts defaults to STANDARD",
        "# ports (postgres 5432, redis 6379, qdrant 6333) and to the legacy `.mount` tree,",
        "# while the compose fragments publish OFFSET ports and the credentials live under",
        "# `.stacks/dev/runtime`. @nestjs/config gives the FIRST file that defines a key",
        "# priority, so a stale `.env.local` silently beats everything generated here.",
        "# Delete it if unsure.",
        "#",
        `# generated: ${new Date().toISOString()}`,
        ""]

    for (const section of buildDerivedSections(ports)) {
        const sectionLines = []
        for (const [key, derivedValue] of section.entries) {
            if (!isKnownKey(key)) {
                skipped.push(key)
                continue
            }
            // `null` marks a generated credential: it only ever comes off disk,
            // and it goes over as a `<KEY>_FILE` pointer rather than a value.
            // Never fall back to the config.ts default here -- that default is
            // the OLD password and would authenticate against nothing.
            if (derivedValue === null) {
                if (!credentials.pointers.has(key)) {
                    unfilled.push(key)
                    continue
                }
                sectionLines.push(`${key}_FILE=${formatEnvValue(credentials.pointers.get(key))}`)
                emitted.push(key)
                continue
            }
            const overridable = !METADATA_OWNED_KEYS.has(key)
            const hasSecret = Object.prototype.hasOwnProperty.call(fromSecrets,
                key)
            const value = (overridable && hasSecret) ? fromSecrets[key] : derivedValue
            if (overridable && hasSecret) {
                usedFromSecrets.add(key)
            }
            sectionLines.push(`${key}=${formatEnvValue(value)}`)
            emitted.push(key)
        }
        if (sectionLines.length > 0) {
            lines.push(`# ${section.title}`,
                ...sectionLines,
                "")
        }
    }

    // ---- secrets: every credential the sections did not already place, as a
    // `<KEY>_FILE` pointer. This is the whole third-party half of the table --
    // stripe, paypal, github, the AI pools -- which config.ts now reads through
    // `parseEnvSecret` by VALUE key, so the bridge names the file and the app
    // opens it.
    const secretLines = []
    for (const [key, pointer] of [...credentials.pointers.entries()].sort()) {
        if (emitted.includes(key) || !isKnownKey(key)) {
            continue
        }
        secretLines.push(`${key}_FILE=${formatEnvValue(pointer)}`)
        emitted.push(key)
    }
    if (secretLines.length > 0) {
        lines.push("# Secrets -- `<KEY>_FILE` pointers, never values. The app reads the",
            "# file itself in parseEnvSecret (src/modules/platform/env/utils/parse-env.ts).",
            ...secretLines,
            "")
    }

    // ---- mount paths: point the app at .stacks / .gitmounts instead of .mount
    const mountLines = []
    const mountSkipped = []
    for (const {
        key, segments
    } of collectMountPathDefaults()) {
        if (segments[0] !== ".mount" || !isKnownKey(key)) {
            continue
        }
        const relocated = relocateMountPath(segments,
            dataMountPath)
        if (relocated === null) {
            mountSkipped.push(key)
            continue
        }
        // a decrypted env file may still pin a path explicitly (e.g. a shared
        // machine keeps a pool somewhere else) -- that wins over the relocation
        const hasSecret = Object.prototype.hasOwnProperty.call(fromSecrets,
            key)
        if (hasSecret) {
            usedFromSecrets.add(key)
        }
        mountLines.push(`${key}=${formatEnvValue(hasSecret ? fromSecrets[key] : relocated)}`)
        emitted.push(key)
    }
    if (mountLines.length > 0) {
        lines.push("# Mount paths -- the app reads credentials and content from the new tree.",
            "# Relative to the repo root (= process.cwd() when npm scripts run).",
            ...mountLines.sort(),
            "")
    }
    if (mountSkipped.length > 0) {
        note(`${mountSkipped.length} .mount default(s) left as they are (not relocated by the plan): ${mountSkipped.sort().join(", ")}`)
    }

    // anything the decrypted env files carry that the sections did not cover
    const extras = Object.keys(fromSecrets)
        .filter((key) => !emitted.includes(key))
        .sort()
    const extrasKnown = extras.filter((key) => isKnownKey(key))
    for (const key of extras) {
        if (!isKnownKey(key)) {
            skipped.push(key)
        }
    }
    if (extrasKnown.length > 0) {
        lines.push("# From .stacks/dev/runtime/env -- keys not derived from metadata.json")
        for (const key of extrasKnown) {
            lines.push(`${key}=${formatEnvValue(fromSecrets[key])}`)
            emitted.push(key)
        }
        lines.push("")
    }

    // never clobber a hand-written file without leaving a copy behind
    if (target.mode === "forced" && existsSync(PATHS.envOverride)) {
        const existing = readFileSync(PATHS.envOverride,
            "utf8")
        if (!existing.startsWith(GENERATED_MARKER)) {
            copyFileSync(PATHS.envOverride,
                PATHS.envOverrideBackup)
            warn("the existing .env.override was NOT generated by this script.")
            warn(`backed it up to ${basename(PATHS.envOverrideBackup)} before overwriting.`)
            warn("that backup is gitignored but still holds real credentials in plaintext --")
            warn("fold anything you still need into .stacks/dev/runtime, then delete it.")
        }
    }

    mkdirSync(dirname(target.path),
        {
            recursive: true
        })
    writeFileSync(target.path,
        lines.join("\n"),
        "utf8")
    const label = relative(REPO_ROOT,
        target.path).split(sep).join("/")
    ok(`wrote ${label} -- ${emitted.length} keys`)
    if (target.mode === "preview") {
        note("the live .env.override was NOT touched: it is hand-written, so this run")
        note("produced a preview instead. Diff the two by key name, then promote with")
        note("`npm run sync -- --write-override` once the new stack is up.")
    }
    if (usedFromSecrets.size > 0) {
        note(`${usedFromSecrets.size} value(s) came from the decrypted stack: ${[...usedFromSecrets].sort().join(", ")}`)
    }
    if (unfilled.length > 0) {
        warn(`${unfilled.length} generated credential(s) have no file yet, so the key was NOT emitted:`)
        for (const key of unfilled.sort()) {
            console.log(`      - ${key}`)
        }
        note("mint them with `npm run secret:gen`, then re-run `npm run sync`.")
    }
    if (credentials.missing.length > 0) {
        note(`credential files still missing under .stacks/dev/runtime/files: ${credentials.missing.sort().join(", ")}`)
    }
    if (skipped.length > 0) {
        warn(`skipped ${skipped.length} key(s) config.ts does not read: ${[...new Set(skipped)].sort().join(", ")}`)
    }
    return {
        emitted
    }
}

// ---------------------------------------------------------------------------
// step 6 -- gitmounts
// ---------------------------------------------------------------------------

/**
 * Returns the repo-relative POSIX path of a declared gitmount.
 * @param name - the gitmount key in metadata.json.
 */
const gitmountPath = (name) => {
    const declared = readMetadataRaw().gitmounts ?? {
    }
    const mount = declared[name]
    return (mount && mount.path) ? mount.path : `.gitmounts/${name}`
}

/**
 * Clones or refreshes every gitmount declared in metadata.json. For this repo
 * that is the private seed-content repo that used to live at `.mount/data`.
 */
const syncGitmounts = () => {
    step(".gitmounts")
    const declared = readMetadataRaw().gitmounts
    if (!declared || Object.keys(declared).length === 0) {
        note("metadata.json declares no gitmounts -- nothing to fetch.")
        return
    }
    if (resolveCommand("git") === null) {
        fail("git is not on PATH.",
            ["every .gitmounts entry is a clone of a git repository.",
                "Install git, then re-run `npm run sync`."])
    }
    for (const [name, mount] of Object.entries(declared)) {
        const label = mount.path || `.gitmounts/${name}`
        const target = join(REPO_ROOT,
            label.split("/").join(sep))
        if (existsSync(join(target,
            ".git"))) {
            const result = run("git",
                ["-C",
                    target,
                    "pull",
                    "--ff-only"])
            if (result.status === 0) {
                ok(`${label} -- ${result.stdout.trim().split(/\r?\n/).pop() || "up to date"}`)
            } else {
                // offline or a dirty working copy is annoying, not fatal
                warn(`could not pull ${label}; keeping the checkout already there.`)
                warn(result.stderr.trim().split(/\r?\n/).pop() ?? "")
            }
            continue
        }
        info(`cloning ${mount.repo} -> ${label}`)
        const args = ["clone",
            "--quiet"]
        if (mount.ref) {
            args.push("--branch",
                mount.ref)
        }
        args.push(mount.repo,
            target)
        const result = run("git",
            args)
        if (result.status !== 0) {
            fail(`could not clone ${mount.repo} into ${label}`,
                [result.stderr.trim().split(/\r?\n/).slice(-3).join("\n    "),
                    "",
                    "It may be a PRIVATE repo -- git has to be authenticated to GitHub:",
                    "  gh auth login          (or configure a git credential helper)",
                    "then re-run `npm run sync`."])
        }
        ok(`${label} cloned`)
    }
}

// ---------------------------------------------------------------------------
// step 7 -- placeholders so boot never ENOENTs
// ---------------------------------------------------------------------------

/**
 * Creates an empty placeholder for every `*.key` the app will read out of
 * `.stacks/dev/runtime/files` but that is not there.
 *
 * The app calls `readFileSync` on these at boot and dies with ENOENT when one is
 * absent -- it has no concept of "this provider is not configured". The old
 * `.mount/terraform` tree papered over that by shipping empty `.key` files; that
 * job moves here. An empty file means what it meant before: the feature behind
 * it is unavailable locally.
 *
 * Structured credentials (`*.json`, `*.yaml`) are deliberately NOT placeheld: an
 * empty one crashes the parser instead of the reader, which is a worse error
 * than the honest ENOENT. Those must come from the migration, so they are
 * reported by name instead.
 * @param table - the loaded credential table (extra filenames, if any).
 * @param dataMountPath - repo-relative POSIX path of the `data` gitmount.
 */
const ensureRuntimeFiles = (table, dataMountPath) => {
    step("runtime placeholders")
    for (const dir of [PATHS.stacksDevRuntimeFiles,
        PATHS.stacksDevRuntimeEnv,
        PATHS.stacksDevRuntimeConfig]) {
        mkdirSync(dir,
            {
                recursive: true
            })
    }

    const wanted = new Set()
    for (const {
        segments
    } of collectMountPathDefaults()) {
        const relocated = relocateMountPath(segments,
            dataMountPath)
        if (relocated === null || !relocated.startsWith(`${RUNTIME_FILES_PREFIX}/`)) {
            continue
        }
        wanted.add(relocated.slice(RUNTIME_FILES_PREFIX.length + 1))
    }
    for (const credential of table.APP_CREDENTIALS) {
        if (credential && typeof credential.file === "string") {
            wanted.add(credential.file)
        }
    }

    const created = []
    const structuredMissing = []
    for (const name of [...wanted].sort()) {
        const target = join(PATHS.stacksDevRuntimeFiles,
            name.split("/").join(sep))
        if (existsSync(target)) {
            continue
        }
        if (!name.endsWith(".key")) {
            structuredMissing.push(name)
            continue
        }
        mkdirSync(dirname(target),
            {
                recursive: true
            })
        writeFileSync(target,
            "",
            "utf8")
        created.push(name)
    }
    if (created.length > 0) {
        note(`created ${created.length} empty placeholder(s) so boot does not ENOENT: ${created.join(", ")}`)
    }
    if (structuredMissing.length > 0) {
        warn(`structured credential file(s) absent -- run the migration, they are NOT placeheld: ${structuredMissing.join(", ")}`)
    }

    // seed.yaml is per-machine dev state, not a secret: it comes from a template
    const seedTarget = join(PATHS.stacksDevRuntimeConfig,
        "seed.yaml")
    if (!existsSync(seedTarget)) {
        if (existsSync(PATHS.seedTemplate)) {
            copyFileSync(PATHS.seedTemplate,
                seedTarget)
            ok("seeded .stacks/dev/runtime/config/seed.yaml from config/seed.example.yaml")
        } else {
            warn("no .stacks/dev/runtime/config/seed.yaml and no config/seed.example.yaml to copy.")
            warn("boot will ENOENT on CONFIG_INIT_SCOPE_MOUNT_PATH until one of them exists.")
        }
    }
    if (created.length === 0 && structuredMissing.length === 0) {
        ok("every runtime file the app reads is present")
    }
}

// ---------------------------------------------------------------------------
// step 8 -- KEYS.md cross-check
// ---------------------------------------------------------------------------

/**
 * Reads `.stacks/dev/runtime/env/KEYS.md` -- the human-maintained roster of what
 * the dev stack is supposed to supply -- and reports, BY NAME ONLY, anything it
 * lists that the generated env bridge did not end up carrying.
 * @param emitted - key names written in step 5.
 */
const crossCheckKeysDoc = (emitted) => {
    step("cross-check KEYS.md")
    const keysDoc = join(PATHS.stacksDevRuntimeEnv,
        "KEYS.md")
    if (!existsSync(keysDoc)) {
        note("no .stacks/dev/runtime/env/KEYS.md -- nothing to cross-check.")
        return
    }
    const {
        literal, patterns
    } = collectConfigKeys()
    const isKnownKey = (key) => literal.has(key)
        || patterns.some((pattern) => pattern.test(key))
    const body = readFileSync(keysDoc,
        "utf8")

    // KEYS.md is a set of markdown tables with a "required" column. Read each row
    // as: the SHOUTING_TOKENS it names, plus whether any cell says "optional".
    // Tokens are then filtered against config.ts, which drops the prose and the
    // placeholder rows ("REDIS_<LANE>_HOST") without needing to parse them.
    const documented = new Map()
    for (const line of body.split(/\r?\n/)) {
        if (!line.trim().startsWith("|")) {
            continue
        }
        const isOptional = /\boptional\b/i.test(line)
        for (const match of line.matchAll(/\b[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)+\b/g)) {
            const key = match[0]
            if (!isKnownKey(key)) {
                continue
            }
            // a key listed required anywhere stays required
            documented.set(key,
                documented.get(key) === true || !isOptional)
        }
    }
    if (documented.size === 0) {
        note("KEYS.md lists no key that config.ts reads -- nothing to compare.")
        return
    }
    const emittedSet = new Set(emitted)
    const missingRequired = [...documented.entries()]
        .filter(([key, required]) => required && !emittedSet.has(key))
        .map(([key]) => key)
        .sort()
    const missingOptional = [...documented.entries()]
        .filter(([key, required]) => !required && !emittedSet.has(key))
        .map(([key]) => key)
        .sort()

    note(`KEYS.md documents ${documented.size} key(s) config.ts reads`)
    if (missingRequired.length === 0) {
        ok("every REQUIRED documented key is present in the generated env bridge")
    } else {
        warn(`${missingRequired.length} REQUIRED key(s) documented in KEYS.md are MISSING:`)
        for (const key of missingRequired) {
            console.log(`      - ${key}`)
        }
        note("supply them via .stacks/dev/runtime/env/*.env.enc and re-run, or mark them")
        note("optional in KEYS.md if the config.ts default is genuinely good enough.")
    }
    if (missingOptional.length > 0) {
        const shown = missingOptional.slice(0,
            12).join(", ")
        const rest = missingOptional.length > 12
            ? `, +${missingOptional.length - 12} more`
            : ""
        note(`${missingOptional.length} optional key(s) not emitted (config.ts defaults apply): ${shown}${rest}`)
    }
}

// ---------------------------------------------------------------------------
// step 9 -- summary
// ---------------------------------------------------------------------------

/**
 * Prints the resolved ports and the commands to run next. Infra is deliberately
 * NOT started here -- `npm run compose` owns that.
 * @param ports - resolved port map.
 * @param offset - metadata.json portOffset, for the human reading this.
 * @param target - `{ path, mode }` the env bridge was written to.
 */
const printSummary = (ports, offset, target) => {
    step("summary")
    const width = Math.max(...Object.keys(ports).map((name) => name.length))
    for (const [name, port] of Object.entries(ports)) {
        info(`${name.padEnd(width)}  ${port}`)
    }
    console.log(`\n    ${green("core")}  http://localhost:${ports.core}`)
    console.log(`    ${dim(`host port = base port + ${offset ?? "portOffset"} (metadata.json)`)}`)
    console.log(`\n    ${cyan("next:")}`)
    console.log("      npm ci")
    console.log("      npm run compose")
    if (target.mode === "preview") {
        console.log("      # then, once the new stack is verified:")
        console.log("      npm run sync -- --write-override")
    }
    console.log("      npm run start:dev\n")
}

// ---------------------------------------------------------------------------
// entrypoint
// ---------------------------------------------------------------------------

const HELP = `
starci-academy-backend dev sync

  npm run sync                     decrypt secrets, generate the env bridge, sync gitmounts
  npm run sync -- --out <path>     write the env bridge to <path> instead
  npm run sync -- --write-override force-write the live .env.override (cutover only)
  npm run sync -- --quiet          near-silent, never fatal (used by the prestart hooks)
  npm run sync -- --help           this text

By default the live .env.override is only written when it does not exist yet, or
when it already carries this script's header. A hand-written one is left alone
and the run produces .env.override.generated instead -- diff that, then promote.

Ports come from metadata.json. Secrets come from the shared master age key at
${MASTER_KEY_PATH} -- never from the repo, never from CI.
`

const main = async () => {
    const args = process.argv.slice(2)
    if (args.includes("--help") || args.includes("-h")) {
        console.log(HELP)
        return
    }
    const knownFlags = ["--write-override",
        "--quiet",
        "--help",
        "-h"]
    let explicitOut = null
    const unknown = []
    for (let i = 0; i < args.length; i += 1) {
        const arg = args[i]
        if (arg === "--out") {
            explicitOut = args[i + 1] ?? null
            if (!explicitOut) {
                fail("--out needs a path argument.",
                    ["example: npm run sync -- --out .env.override.preview"])
            }
            i += 1
            continue
        }
        if (arg.startsWith("--out=")) {
            explicitOut = arg.slice("--out=".length)
            continue
        }
        if (!knownFlags.includes(arg)) {
            unknown.push(arg)
        }
    }
    if (unknown.length > 0) {
        fail(`unknown argument(s): ${unknown.join(", ")}`,
            ["run `npm run sync -- --help` for the supported flags."])
    }
    QUIET = args.includes("--quiet")
    const forceOverride = args.includes("--write-override")

    if (!QUIET) {
        console.log(cyan("starci-academy-backend :: sync"))
    }
    const {
        ports, offset
    } = readMetadata()
    const masterKeyPath = locateMasterKey()
    ensureTools()
    const table = await loadCredentialTable()
    // Only `runtime/env` carries KEY=VALUE pairs. `runtime/files` is decrypted to
    // disk for the app to read BY PATH; folding it into the env bridge would
    // inline a whole service-account JSON as an env var.
    const decryptedEnvFiles = decryptDevStack(masterKeyPath)
        .filter((file) => file.startsWith(PATHS.stacksDevRuntimeEnv)
            && file.endsWith(".env"))
    const credentials = readCredentialValues(table)
    const dataMountPath = gitmountPath("data")
    const target = resolveTarget(explicitOut,
        forceOverride)
    const {
        emitted
    } = writeEnvBridge(ports,
        decryptedEnvFiles,
        credentials,
        dataMountPath,
        target)
    // Skipped under --quiet: this clones/pulls over the network, and the prestart
    // hook must not turn `npm run start:dev` into a network-dependent command.
    if (!QUIET) {
        syncGitmounts()
    }
    ensureRuntimeFiles(table,
        dataMountPath)
    crossCheckKeysDoc(emitted)
    if (!QUIET) {
        printSummary(ports,
            offset,
            target)
    }
}

main()
