
services:
  core:
    build:
      context: ../..
      dockerfile: apps/core/Dockerfile
    environment:
      # PostgreSQL
      POSTGRESQL_PRIMARY_HOST: ${POSTGRESQL_PRIMARY_HOST}
      POSTGRESQL_PRIMARY_PORT: ${POSTGRESQL_PRIMARY_PORT}
      POSTGRESQL_PRIMARY_PASSWORD: ${POSTGRESQL_PRIMARY_PASSWORD}

      # Qdrant
      QDRANT_URL: ${QDRANT_URL}
      QDRANT_API_KEY: ${QDRANT_API_KEY}

      # Redis
      REDIS_BULLMQ_HOST: ${REDIS_BULLMQ_HOST}
      REDIS_BULLMQ_PORT: ${REDIS_BULLMQ_PORT}
      REDIS_BULLMQ_PASSWORD: ${REDIS_BULLMQ_PASSWORD}

      REDIS_THROTTLER_HOST: ${REDIS_THROTTLER_HOST}
      REDIS_THROTTLER_PORT: ${REDIS_THROTTLER_PORT}
      REDIS_THROTTLER_PASSWORD: ${REDIS_THROTTLER_PASSWORD}

      REDIS_ADAPTER_HOST: ${REDIS_ADAPTER_HOST}
      REDIS_ADAPTER_PORT: ${REDIS_ADAPTER_PORT}
      REDIS_ADAPTER_PASSWORD: ${REDIS_ADAPTER_PASSWORD}

      REDIS_CACHE_HOST: ${REDIS_CACHE_HOST}
      REDIS_CACHE_PORT: ${REDIS_CACHE_PORT}
      REDIS_CACHE_PASSWORD: ${REDIS_CACHE_PASSWORD}

      CORS_ORIGIN_1: ${CORS_ORIGIN_1} 

      CORE_PORT: ${CORE_PORT}
    volumes:
      - /root/academy/.mount:/usr/src/app/.mount