services:
  cli:
    build:
      context: ../..
      dockerfile: apps/cli/Dockerfile
    env_file:
      - ../../.env.docker
    volumes:
      - ../../.mount:/usr/src/app/.mount 

# docker build -t kanibot/cli:latest -f apps/cli/Dockerfile . && docker push kanibot/cli:latest
# docker compose -f apps/cli/compose.yaml up --build -d
