server {
    listen 80;
    resolver 127.0.0.11 valid=1s;

    location / {
        set $backend "http://scaling-service:3000";
        proxy_pass $backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
