version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: es
    environment:
      - node.name=es-node-1
      - cluster.name=es-cluster
      - discovery.type=single-node
      # security (ES 8 enabled)
      - ELASTIC_PASSWORD=123456
      # JVM
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      # disable TLS
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://host.docker.internal:9200
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN=AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjpadjdLdzVuMlFCYTVxVlZ4V250cVNn
volumes:
  es_data:

# docker exec -it es bin/elasticsearch-service-tokens create elastic/kibana kibana-token