# =========================
# Core server config
# =========================

port: 4222

# HTTP monitoring
http: 8222

# Server name
server_name: nats-1

# =========================
# Authentication
# =========================

authorization {
  token: "starci@2026"
}

# =========================
# Logging
# =========================

debug: false
trace: false
logtime: true

# =========================
# Cluster config
# =========================

cluster {
  name: nats-cluster
  port: 6222
}