# .github/workflows/deploy-core-vps.yml
name: Deploy Core VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    environment: core-vps

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show docker info
        run: |
          docker --version
          docker compose version

      - name: Deploy core with Docker Compose
        env:
          POSTGRESQL_PRIMARY_HOST: ${{ secrets.POSTGRESQL_PRIMARY_HOST }}
          POSTGRESQL_PRIMARY_PORT: ${{ secrets.POSTGRESQL_PRIMARY_PORT }}
          POSTGRESQL_PRIMARY_PASSWORD: ${{ secrets.POSTGRESQL_PRIMARY_PASSWORD }}

          QDRANT_URL: ${{ secrets.QDRANT_URL }}
          QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}

          REDIS_BULLMQ_HOST: ${{ secrets.REDIS_BULLMQ_HOST }}
          REDIS_BULLMQ_PORT: ${{ secrets.REDIS_BULLMQ_PORT }}
          REDIS_BULLMQ_PASSWORD: ${{ secrets.REDIS_BULLMQ_PASSWORD }}

          REDIS_THROTTLER_HOST: ${{ secrets.REDIS_THROTTLER_HOST }}
          REDIS_THROTTLER_PORT: ${{ secrets.REDIS_THROTTLER_PORT }}
          REDIS_THROTTLER_PASSWORD: ${{ secrets.REDIS_THROTTLER_PASSWORD }}

          REDIS_ADAPTER_HOST: ${{ secrets.REDIS_ADAPTER_HOST }}
          REDIS_ADAPTER_PORT: ${{ secrets.REDIS_ADAPTER_PORT }}
          REDIS_ADAPTER_PASSWORD: ${{ secrets.REDIS_ADAPTER_PASSWORD }}

          REDIS_CACHE_HOST: ${{ secrets.REDIS_CACHE_HOST }}
          REDIS_CACHE_PORT: ${{ secrets.REDIS_CACHE_PORT }}
          REDIS_CACHE_PASSWORD: ${{ secrets.REDIS_CACHE_PASSWORD }}

          CORS_ORIGIN_1: ${{ vars.CORS_ORIGIN_1 }}

          CORE_PORT: ${{ vars.CORE_PORT }}
 
          KEYCLOAK_URL: ${{ secrets.KEYCLOAK_URL }}
          KEYCLOAK_REDIRECT_URI: ${{ secrets.KEYCLOAK_REDIRECT_URI }}

          MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}

          ELASTICSEARCH_NODE: ${{ secrets.ELASTICSEARCH_NODE }}
          ELASTICSEARCH_PASSWORD: ${{ secrets.ELASTICSEARCH_PASSWORD }}
        run: |
          docker compose -f apps/core/vps-compose.yaml down || true
          docker compose -f apps/core/vps-compose.yaml up --build -d 